### ISSUE TITLE
AS3 tenant default route domain - not working

### ISSUE THREAD

**Issue by sgops** [F5Networks/k8s-bigip-ctlr#1011]
#### Description
We need to deploy via AS3 and use the "defaultRouteDomain" so that the CIS discovered pool members are in the right Route Domain. The BIG-IP uses AS3 f5-appsvcs-3.13.1-1.noarch.

When removing the "defaultRouteDomain" the declaration works.
When posting the declaration via Postman with the "defaultRouteDomain" it works as well.

#### Kubernetes Version
v1.14.6

#### Controller Version
f5networks/k8s-bigip-ctlr:1.10

#### BIG-IP Version
14.1.2

#### Diagnostic Information
The contoller logs the error from the BIG-IP:
```
2019/08/29 13:41:21 [ERROR] [as3_log] Big-IP Response error &{422 Unprocessable Entity 422 HTTP/1.1 1 1 map[X-Content-Type-Options:[nosniff] Content-Security-Policy:[default-src 'self' https://sentinel.whitehatsec.com https://sentinel.whitehatsec.eu https://api.ctscloud.com https://key.ctscloud.com 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' data: https://sentinel.whitehatsec.com https://sentinel.whitehatsec.eu https://api.ctscloud.com https://key.ctscloud.com http://127.4.1.1 http://127.4.2.1] Date:[Thu, 29 Aug 2019 13:41:19 GMT] Set-Cookie:[BIGIPAuthCookie=REDACTED; path=/; Secure; HttpOnly BIGIPAuthUsernameCookie=admin; path=/; Secure; HttpOnly] X-Frame-Options:[SAMEORIGIN] Pragma:[no-cache] Cache-Control:[no-store no-cache must-revalidate] Server:[Jetty(9.2.22.v20170606)] Strict-Transport-Security:[max-age=16070400; includeSubDomains] Content-Length:[1165] Content-Type:[application/json; charset=UTF-8] Expires:[-1] X-Xss-Protection:[1; mode=block]] 0xc000ea6600 1165 [] false false map[] 0xc0009b8000 0xc0007ce0b0}
```

Example ConfigMap:
```yaml
apiVersion: v1
data:
  template: |-
    {
  "class": "AS3",
  "action": "deploy",
  "persist": true,
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.13.0",
    "id": "1847a369-5a25-4d1b-8cad-5740988d4423",
    "label": "APP Template",
    "remark": "HTTP application",
    "APP": {
      "class": "Tenant",
      "defaultRouteDomain": 2,
      "app": {
        "class": "Application",
        "template": "generic",
        "app_80_vs": {
          "class": "Service_HTTP",
          "remark": "app",
          "virtualAddresses": [
            "10.165.36.141%2"
          ],
          "virtualPort": 80,
          "profileTCP": {
            "bigip": "/Common/f5-tcp-lan"
          },
          "pool": "app_pool"
        },
        "app_pool": {
          "class": "Pool",
          "members": [
            {
              "servicePort": 80,
              "serverAddresses": []
            }
          ]
        }
      }
    }
  }
}
kind: ConfigMap
metadata:
  annotations:
  labels:
    as3: "true"
    cattle.io/creator: norman
    f5type: virtual-server
  name: nginx-as3
  namespace: default

```
