### ISSUE TITLE
BIG-IP Controller cannot detect to increase or decrease number of pods

### ISSUE THREAD

**Issue by altblanc** [F5Networks/k8s-bigip-ctlr#1019]
#### Description
With using AS3, k8s-bigip-ctlr cannot detect to change the number of pods.  
Our k8s-bigip-ctlr is working on cluster-mode.I followed [this document](https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-k8s-as3.html#cis-and-partitions) for deploying AS3 object.  
First detection is correct, but if I change my deployment, k8s-bigip-ctlr cannot detect it, so pod's ips are not changed and pool is down.

here is my AS3 configmap.

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: as3-declaration
  namespace: kube-system
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "as3-declaration",
        "label": "application",
        "remark": "HTTPS definition for app1",
        "AS3": {
          "class": "Tenant",
          "app1": {
            "class": "Application",
            "template": "https",
            "serviceMain": {
              "class": "Service_HTTPS",
              "redirect80": false,
              "iRules": [
                {"bigip":"/Common/iRule1"},
                {"bigip":"/Common/iRule2"}
              ],
              "virtualAddresses": [
                "10.3.115.22"
              ],
              "serverTLS": {"bigip":"/Common/app1"},
              "profileHTTP": {
                "bigip": "/Common/http_for_https"
              },
              "profileHTTP2": {
                "bigip": "/Common/http2_client"
              },
              "pool": "app1_pool"
            },
            "app1_pool":{
              "class":"Pool",
              "monitors":[
                "http"
              ],
              "members":[
                {
                  "servicePort":8080,
                  "serverAddresses":[]
                }
              ]
            }
          },
          "app2": {
            "class": "Application",
            "template": "generic",
            "app2": {
              "class": "Service_HTTPS",
              "redirect80": false,
              "virtualAddresses": [
                "10.3.115.23"
              ],
              "iRules": [
                {"bigip":"/Common/iRule1"},
                {"bigip":"/Common/iRule2"}
              ],
              "serverTLS": {"bigip":"/Common/app2"},
              "profileHTTP": {
                "bigip": "/Common/http_for_https"
              },
              "profileHTTP2": {
                "bigip": "/Common/http2_client"
              },
              "pool": "app2_pool"
            },
            "app2_pool":{
              "class":"Pool",
              "monitors":[
                "http"
              ],
              "members":[
                {
                  "servicePort":8080,
                  "serverAddresses":[]
                }
              ]
            }
          },
          "app3": {
            "class": "Application",
            "template": "generic",
            "menu": {
              "class": "Service_HTTPS",
              "redirect80": false,
              "virtualAddresses": [
                "10.3.115.24"
              ],
              "iRules": [
                {"bigip":"/Common/iRule1"},
                {"bigip":"/Common/iRule1"}
              ],
              "serverTLS": {"bigip":"/Common/app3"},
              "profileHTTP": {
                "bigip": "/Common/http_for_https"
              },
              "profileHTTP2": {
                "bigip": "/Common/http2_client"
              },
              "pool": "app3_pool"
            },
            "app3_pool":{
              "class":"Pool",
              "monitors":[
                "http"
              ],
              "members":[
                {
                  "servicePort":8080,
                  "serverAddresses":[]
                }
              ]
            }
          }
        }
      }
    }
```

my deployment and service are below.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: application
  labels:
    app.kubernetes.io/name: app1
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: app1
    tier: frontend
spec:
  replicas: 50
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      namespace: application
      labels:
        app.kubernetes.io/name: app1
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: app1
        tier: frontend
        app: app1
    spec:
      containers:
      - name: app1
        image: my.private.registry/applications/app1:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
          - name: app1-secrets
            mountPath: /app1/config/credentials.yml.enc
            subPath: credentials.yml.enc
          - name: app1-secrets
            mountPath: /app1/config/master.key
            subPath: master.key
          - name: pv-app1-volume
            mountPath: "/mnt/nfs"
      volumes:
        - name: app1-secrets
          secret:
            secretName: app1-sct
            defaultMode: 420 
        - name: pv-app1-volume
          persistentVolumeClaim:
            claimName: pv-app1
---
kind: Service
apiVersion: v1
metadata:
  name: app1
  namespace: application
  labels:
    app.kubernetes.io/name: app1
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: app1
    tier: frontend
    app: app1
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: app1
    cis.f5.com/as3-pool: app1_pool
spec:
  selector:
    app: app1
  ports:
  - name: http8080
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

```

#### Kubernetes Version
1.13.1

#### Controller Version
1.10.0

#### BIG-IP Version
1.14.1
