### ISSUE TITLE
Set up RBAC Authentication Unclear

### ISSUE THREAD

**Issue by grmarxer-1** [F5Networks/k8s-bigip-ctlr#1084]
#### Description
https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html
In section Set up RBAC Authentication the exact command is provided to create the service account.  However,  for the cluster role binding all that is provided is a url.  A specific closterrole binding command should be provided to match the service account command provided above.  In addition a brief explanation should be provided for each of these commands so a generic user will understand what they are doing and why they are required for CIS to work properly.

**Comment by ssurenr** [comment]
I think it will be redundant information as the declaration beneath that section conveys the same. This will increase the documentation length unnecessarily. I agree it is complicated for a user who is new to kubernetes itself. However, the best thing to be is to point the user to kubernetes documentation, which is what the current doc is doing.

**Comment by grmarxer-1** [comment]
Since we provide... kubectl create serviceaccount bigip-ctlr -n kube-system

How is adding ...
kubectl create clusterrolebinding k8s-bigip-ctlr-clusteradmin --clusterrole=cluster-admin --serviceaccount=kube-system:k8s-bigip-ctlr

making the documentation any longer?  In addition customers appreciate thorough documentation regardless of length.

**Comment by ssurenr** [comment]
Since we are providing the following YAML, which is equivalent to the command-line option you mentioned, wouldn't that be sufficient?

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole-binding
  namespace: <controller_namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-ctlr-clusterrole
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: <controller_namespace>
```

If we keep adding the CLI command as well as YAML declaration for the same operation, that will increase the doc length.
