### ISSUE TITLE
Update F5 configuration after remove and create Ingress resource

### ISSUE THREAD

**Issue by wheestermanstoyota** [F5Networks/k8s-bigip-ctlr#1093]
#### Description
Update F5 configuration after remove and create Ingress resource

#### Kubernetes Version
v1.14.7-docker-1 (Docker-EE 3.0)

#### Controller Version
1.11.1

#### Diagnostic Information

Ingress resource:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tme-ing-jetty-deploytest
  namespace: tme-ns-jetty-dev
  annotations:
    # See the k8s-bigip-ctlr documentation for information about
    # all Ingress Annotations
    # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest/#supported-ingress-annotations
    virtual-server.f5.com/ip: "10.100.4.110"
    virtual-server.f5.com/partition: "KuberNetes"
    virtual-server.f5.com/balance: "round-robin"
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/health: |
      [
        {
          "type": "http",
          "path": "internal-docker-k8s-jetty-deploytest-dev.toyota-europe.com/",
          "send": "HEAD HTTP/1.0",
          "interval": 5,
          "timeout":  10
        }
      ]    
spec:
  rules:
  - host: internal-docker-k8s-jetty-deploytest-dev.toyota-europe.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tme-svc-jetty-deploytest
          servicePort: 8080
```

We have two pods running (deployment + service). The we create the Ingress using kubectl create..., Inside the F5 console I see almost immediately the pool, but is red because no members inside. I takes around 2 minutes before the pool comes green with the members. I woudl expect that this should almost immediate because all pods were running. So why does it takes so much time?

Same behaviour when I remove the Ingress. I takes more then a minute before the pool is removed on F5 level.

Regards
Walter
