### ISSUE TITLE
[BUG]Both clientssl annotation and cert/key provided for Route in log

### ISSUE THREAD

**Issue by sbarre-esit** [F5Networks/k8s-bigip-ctlr#1212]
#### Description

Following line gets logged every ~5 seconds even though only the annotation is specified:

```
2020/03/16 21:25:50 [WARNING] Both clientssl annotation and cert/key provided for Route: django-psql-example, using annotation.
```

Seems to be the same as #805

#### Kubernetes Version
```console
# oc version
Client Version: openshift-clients-4.3.0-201910250623-88-g6a937dfe
Server Version: 4.3.1
Kubernetes Version: v1.16.2
```

#### Controller Version
```console
# oc get pods -n f5-bigip -o yaml f5-bigip-bla-56db6597bc-dwr7r | grep image:
    image: f5networks/k8s-bigip-ctlr:1.14.0
    image: docker.io/f5networks/k8s-bigip-ctlr:1.14.0
```

#### BIG-IP Version
```console
root@(bla)(cfg-sync Changes Pending)(Active)(/)(tmos)# show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Tue Nov  5 10:09:50 PST 2019
```

#### Diagnostic Information
**Route**
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/host.generated: "true"
    virtual-server.f5.com/clientssl: /Common/bla_clientssl
  creationTimestamp: "2020-03-16T21:10:24Z"
  labels:
    app: django-psql-example
    f5type: App1
    template: django-psql-example
  name: django-psql-example
  namespace: mysecureapp
spec:
  host: django-psql-example-mysecureapp.bla.ca
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: django-psql-example
    weight: 100
  wildcardPolicy: None
```

**Controller**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-bigip-bla
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:1.14.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=1.2.3.4",
            "--bigip-partition=openshift-rd1",
            "--pool-member-type=cluster",
            "--openshift-sdn-name=/Common/openshift_vxlan",
            "--manage-routes=true",
            "--route-label=App1",
            "--route-vserver-addr=1.2.3.5",
            "--insecure=true",
            ]
```
