### ISSUE TITLE
Using Let'sEncrypt - Issuing/renewing SSL certificates

### ISSUE THREAD

**Issue by mr-worf** [F5Networks/k8s-bigip-ctlr#1256]
#### Description
Hi, 
I am trying to configure automatic Let'sEncrypt TLS issuing/renewing with CIS and Kubernetes using jetstack/cert-manager. But the client SSL profile with SSL certificate provided in k8s secret has not been created and has not been attached to virtual server.

#### Kubernetes Version
v1.17.2

#### Controller Version
v1.14.0

#### BIG-IP Version
14.1.2.3 Build 0.0.5

#### Diagnostic Information
Cert manager create TLS certificate and store this cert as k8s secret.

```
$ kubectl get secrets -n default secret-xyz-tls -oyaml
apiVersion: v1
data:
  ca.crt: ""
  tls.crt: <base64-encoded_cert>
  tls.key: <base64-encoded_key>
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: '*.example.xyz,example.xyz'
    cert-manager.io/certificate-name: wild-example-com
    cert-manager.io/common-name: example.xyz
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-name: acme-issuer
    cert-manager.io/uri-sans: ""
  creationTimestamp: "2020-04-05T12:40:35Z"
  name: example-com-tls
  namespace: default
  resourceVersion: "7936381"
  selfLink: /api/v1/namespaces/default/secrets/secret-xyz-tls
  uid: 12345678-ab12-34ab-1abc-d3da4733964e
type: kubernetes.io/tls
```
Then this k8s secret has been used as resource in ingress definition,
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: f5-httpv1-ingress
  namespace: default
  annotations:
    virtual-server.f5.com/ip: "xx.xx.xx.xx"
    virtual-server.f5.com/partition: "k8s_AS3"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/allow-http: "false"
    kubernetes.io/ingress.class: "f5"
    virtual-server.f5.com/https-port: "443"
spec:
  tls:
    - secretName: "/Common/SNIbase"
    - secretName: secret-xyz-tls
  rules:
  - host: mas3.example.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: f5-httpv1
          servicePort: 8080
```
F5  CIS config:
```
Name:           k8s-bigip-ctlr-deployment-5b8458cd9-z5nwl
Namespace:      kube-system
Priority:       0
Node:           node-worker2/xx.xx.xx.xx
Start Time:     Thu, 09 Apr 2020 09:12:23 +0200
Labels:         app=k8s-bigip-ctlr
                pod-template-hash=5b8458cd9
Annotations:    cni.projectcalico.org/podIP: 10.144.58.246/32
                prometheus.io/path: /metrics
                prometheus.io/port: 8080
                prometheus.io/scrape: true
Status:         Running
IP:             10.144.58.246
Controlled By:  ReplicaSet/k8s-bigip-ctlr-deployment-5b8458cd9
Containers:
  k8s-bigip-ctlr:
    Container ID:  docker://0779764b43d68805de557d476e0d49655010ff3e1c24345ec645a60cf7ebe9d8
    Image:         f5networks/k8s-bigip-ctlr:1.14.0
    Image ID:      docker-pullable://f5networks/k8s-bigip-ctlr@sha256:25bdfc947ed4cdd172a68e37c51dbaa8ca87fcbc4d894622b42a260755a2bf68
    Port:          <none>
    Host Port:     <none>
    Command:
      /app/bin/k8s-bigip-ctlr
    Args:
      --bigip-username=$(BIGIP_USERNAME)
      --bigip-password=$(BIGIP_PASSWORD)
      --bigip-url=xx.xx.xx.xx
      --bigip-partition=k8s
      --pool-member-type=cluster
      --log-level=DEBUG
      --log-as3-response=true
      --insecure=true
      --agent=as3
      --resolve-ingress-names=LOOKUP
      --namespace=default
    State:          Running
      Started:      Thu, 09 Apr 2020 09:12:38 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      BIGIP_USERNAME:  <set to the key 'username' in secret 'bigip-login'>  Optional: false
      BIGIP_PASSWORD:  <set to the key 'password' in secret 'bigip-login'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from k8s-bigip-ctlr-token-rxb2h (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  k8s-bigip-ctlr-token-rxb2h:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  k8s-bigip-ctlr-token-rxb2h
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
Some log captured from controller:
```

k8s-bigip-ctlr 2020/04/23 18:40:19 [DEBUG Found endpoints for backend {ServiceName:f5-httpv1 ServicePort:8080 Namespace:default}: [{10.144.235.133 8080 user-enabled} {10.144.58.217 8080 user-enabled}]
k8s-bigip-ctlr 2020/04/23 18:40:19 [WARNING Overwriting existing entry for backend {ServiceName:f5-httpv1 ServicePort:8080 Namespace:default}
k8s-bigip-ctlr 2020/04/23 18:40:19 [DEBUG Updated 1 of 2 virtual server configs, deleted 0
k8s-bigip-ctlr 2020/04/23 18:40:19 [DEBUG AS3 Template is Validated Successfully 
k8s-bigip-ctlr 2020/04/23 18:40:19 [DEBUG [AS3 No Change in the Configuration
k8s-bigip-ctlr 2020/04/23 18:40:19 [DEBUG Finished syncing virtual servers {Namespace:default ServiceName:f5-httpv1 AS3Name: AS3Data:} (140.089275ms)
k8s-bigip-ctlr 2020/04/23 18:40:20 [ERROR Error parsing ConfigMap default_f5-as3-declaration
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Configured rule: {ingress_mas3.example.xyz__ingress_default_f5-httpv1 mas3.example.xyz/ 0 [0xc0006ebc80 [0xc001720940}
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Configured policy: {ingress_xx-xx-xx-xx_80 k8s_AS3  [forwarding  true [http [0xc0006ebce0 /Common/first-match}
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG TLS: Applying HTTP redirect iRule.
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Configured rule: {ingress_mas3.example.xyz__ingress_default_f5-httpv1 mas3.example.xyz/ 0 [0xc001042180 [0xc000258300}
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Configured policy: {ingress_xx-xx-xx-xx_443 k8s_AS3  [forwarding  true [http [0xc0010421e0 /Common/first-match}
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG No Secret with name '/Common/SNIbase' in namespace 'default', parsing secretName as path instead.
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG No Secret with name 'secret-xyz-tls' in namespace 'default', parsing secretName as path instead.
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Partition not provided in profile 'secret-xyz-tls', using default partition 'k8s_AS3'
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Updated 0 of 0 virtual server configs, deleted 0
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Finished syncing virtual servers {Namespace:default ServiceName:f5-hello-world-web AS3Name: AS3Data:} (2.288052ms)
k8s-bigip-ctlr 2020/04/23 18:40:20 [ERROR Error parsing ConfigMap default_f5-as3-declaration
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Configured rule: {ingress_mas3.example.xyz__ingress_default_f5-httpv1 mas3.example.xyz/ 0 [0xc000770ba0 [0xc000eca480}
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Configured policy: {ingress_xx-xx-xx-xx_80 k8s_AS3  [forwarding  true [http [0xc000770c60 /Common/first-match}
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG TLS: Applying HTTP redirect iRule.
k8s-bigip-ctlr 2020/04/23 18:40:20 [DEBUG Found endpoints for backend {ServiceName:f5-httpv1 ServicePort:8080 Namespace:default}: [{10.144.235.133 8080 user-enabled} {10.144.58.217 8080 user-enabled}]
```
This is maybe the most interesting log record
```
No Secret with name 'secret-xyz-tls' in namespace 'default', parsing secretName as path instead.
```
It seems that controller does not see this secret in 'default' namespaces, but this secret is definitely there.

Can sombody help with this issue?

Regards

**Comment by mr-worf** [comment]
Hi,
There is a problem with ClusterRole suggested by doc on link https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html
``` 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "events", "ingresses/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  resourceNames: ["<secret-containing-bigip-login>"]
  verbs: ["get", "list", "watch"]
```
I changed ClusterRole to following  
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "events", "ingresses/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
```
I got my SSL secret deployed to BigIP :)
But, I was not able to deploy multiple SSL secrets to one Ingress, only one.
