### ISSUE TITLE
BigIP AS3 responds with Shared/Ingress_10_5_68_71_443/rules/0/name: should match format "f5name"

### ISSUE THREAD

**Issue by Timoses** [F5Networks/k8s-bigip-ctlr#1272]
#### Description
Using k8s-bigip-ctlr deployed with Helm chart and arguments:
```
        - --agent
        - as3
        - --log-as3-response
```
(Trying `--agent=as3` due to https://github.com/F5Networks/k8s-bigip-ctlr/issues/975 with CCCL).

Using a simple ingress resource (see below) k8s-bigig-ctlr logs the following error:
```
2020/04/30 16:16:11 [ERROR] [AS3] Big-IP Responded with code: 422
2020/04/30 16:16:11 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/mypartition_AS3/Shared/Ingress_10_5_68_71_443/rules/0/name: should match format "f5name"] message:declaration is invalid]
```

Is there any way I can inspect the transmitted AS3 declaration? That could help in identifying the cause.

#### Kubernetes Version
v1.17.4

#### Controller Version
v1.14.0

#### BIG-IP Version
Version: 14.1.2.3 Build 0.0.5
AS3 Package version: f5-appsvcs-3.14.0-4.noarch

#### Diagnostic Information
Ingress resource:
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      virtual-server.f5.com/ip: controller-default
    name: argocd-server-http-ingress
    namespace: argocd
  spec:
    rules:
    - host: argocd.test.int
      http:
        paths:
        - backend:
            serviceName: argocd-server
            servicePort: 80
    tls:
    - hosts:
      - argocd.test.int
      secretName: argocd-secret
```

**Comment by mdditt2000** [comment]
Hi @Timoses what AS3 package are you using?

**Comment by mdditt2000** [comment]
hi @Timoses your issue with the name: argocd-server-http-ingress. Please make it smaller. The AS3 API is running into a char lengh issue. I did some testing using name argocd-http and it worked great! Here is the repo i created https://github.com/mdditt2000/kubernetes-1-18/tree/master/cis%201.14/github-issue/%231272

**Comment by mdditt2000** [comment]
Let me know if you have any additional question.

**Comment by Timoses** [comment]
Thanks a lot for the feedback @mdditt2000 ! I'll give it a try asap next week.

As already mentioned: It would be great if the `k8s-bigip-ctlr` would somehow enable access to the AS3 declaration that is transmitted to F5 BigIP.
That way one could validate it e.g. via https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/validate.html and do some first-hand troubleshooting.

**Comment by Timoses** [comment]
> 
> 
> hi @Timoses your issue with the name: argocd-server-http-ingress. Please make it smaller. The AS3 API is running into a char lengh issue. I did some testing using name argocd-http and it worked great! Here is the repo i created https://github.com/mdditt2000/kubernetes-1-18/tree/master/cis%201.14/github-issue/%231272

Alright, I tested it and the following works without problem:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/ip: controller-default
  name: argocd
spec:
  backend:
    serviceName: argocd
    servicePort: 8080
```

Also this does:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/ip: controller-default
  name: argocd
spec:
  rules:
  - host: a.test.int
      http:
        paths:
        - backend:
            serviceName: argocd-server
            servicePort: 80
```


But this does not:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/ip: controller-default
  name: argocd
spec:
  rules:
  - host: argocd.cluster-dev-1.test.int
      http:
        paths:
        - backend:
            serviceName: argocd-server
            servicePort: 80
```

So the `host` hostname is also too long as well.

Does it make sense to limit this? Longer domain names should be quite common.

**Off-Topic**: For us currently f5 k8s ctlr is simply not usable as also this has not been fixed yet: https://github.com/F5Networks/k8s-bigip-ctlr/issues/975. Perhaps CCCL won't even get any fixes any longer as AS3 is the new approach?
