### ISSUE TITLE
You can used docker inspect see the Bigip username and password!

### ISSUE THREAD

**Issue by sober-wang** [F5Networks/k8s-bigip-ctlr#1321]
#### Setup Details
 Build: f5networks/k8s-bigip-ctlr:1.14.0     
 Agent Mode: AS3/CCCL       
 Orchestration: K8S   
 Orchestration Version: v1.16 v1.13.5       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: NSX-T and Flannel
Containers Engine:  Docker v18.06 v18.09

#### Description  
When I deploy a f5-cccl pod on my k8s cluster. next I find the machine this pod running on. I can see the bigip IP address , user name and password

I think the so horrible. My company network safety department tell me the incompatible about safety production. 

 
#### Steps To Reproduce
```shell
# On k8s apiserver user the command 
kubectl get pods -o wide 

NAME                                           READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
<YOUR_F5_CCCL_DEPLOYMENT_NAME>-5ffb54497d-7zgsm   1/1     Running   167        5d22h   10.244.1.137   192.1.1.10   <none>           <none>
<YOUR_F5_CCCL_DEPLOYMENT_NAME>-5ffb54497d-lzrrh   1/1     Running   157        5d22h   10.244.7.80    192.168.1.11   <none>           <none>

# Let's go to k8s node this pod running on 
ssh root@192.1.1.10 
docker inspect $(docker ps |grep -v paus | grep <YOUR_F5_CCCL_DEPLOYMENT_NAME> | awk '{print $1}') --fromat '{{ .Args }}'

# stdout  information 
[--bigip-username=<BIGIP_USERNAME> --bigip-password=<BIGIP_PASSWORD> --bigip-url=<BIGIP_IP_ADDRESS> --bigip-partition=k8s_test01 --pool-member-type=cluster --insecure=true]
```
Amazing !!!
You can sea the bigip IP address and bigip username ,password.

**Comment by mdditt2000** [comment]
@sober-wang please make sure you use K8S secret when provide the big-ip creds for CIS. https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-secrets.html#secret-bigip-login

**Comment by sober-wang** [comment]
Yes, I used k8s secret resource.
```shell
kubectl create secret generic bigip-login --namespace kube-system --from-literal=username=admin --from-literal=password=admin
```

```yaml
# my f5-cccl deployment
····
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              name: bigip-login
              key: username
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bigip-login
              key: password
        command:
        - /app/bin/k8s-bigip-ctlr
        args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=<F5_IP>
        - --bigip-partition=<APP_PARTITION> # app_id ns ,no number, eg: 10086 ,part ywdt
        - --pool-member-type=cluster
        - --insecure=true

····
```
