### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by rushins** [F5Networks/k8s-bigip-ctlr#1382]
#### Description  
  deploying f5-controller.yaml getting error

#### Steps To Reproduce
kubectl create -f f5-controller.yaml
---
no matches for kind "Deployment" in version "extensions/v1beta1"

i changed extensions/v1beta1 to apps/v1 , however it is not creating due to "missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec" 

any solution to fix this.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by agupta49** [comment]
@rushins Can you please share your environment details and f5-controller.yaml configuration.

**Comment by mdditt2000** [comment]
@rushins please use the new apiversion apps/1 as "extensions/v1beta1" is depreciate as of K8S 1.16  

```
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
```

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by mdditt2000** [comment]
Here is a working example
https://github.com/mdditt2000/kubernetes-1-18/blob/master/cis%202.0/crd/big-ip-92-cluster/cis-deployment/f5-cluster-deployment.yaml

**Comment by rushins** [comment]
yes i tried that 

> @rushins please use the new apiversion apps/1 as "extensions/v1beta1" is depreciate as of K8S 1.16
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata: 
>   name: k8s-bigip-ctlr-deployment
>   namespace: kube-system
> ```
> 
> https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

i think i mentioned that i tried and it complains about selector which also i tried. here is the changes i made but the selector seems bothering
-----

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
-----

**Comment by mdditt2000** [comment]
what version of K8S are you using?

You also need the following with the API change if you are using K8S 1.16 and above

```
apiVersion: apps/v1 ---------------- You need to add this section
kind: Deployment
metadata: 
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec: 
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector: ---------------- You need to add this section
    matchLabels: ---------------- You need to add this section
      app: k8s-bigip-ctlr ---------------- You need to add this section
```
