### ISSUE TITLE
Optional health check paramaters don't appear to be optional

### ISSUE THREAD

**Issue by sbarre-esit** [F5Networks/k8s-bigip-ctlr#1440]
#### Setup Details
 CIS Version : 2.1.0
 Build: f5networks/k8s-bigip-ctlr:2.1.0
 BIGIP Version: BIG-IP 14.1.2.6 Build 0.0.2 Point Release 6
 AS3 Version: f5-appsvcs-3.20.0-3.noarch
 Agent Mode: AS3
 Orchestration: OSCP
 Orchestration Version: v4.4
 Pool Mode: Cluster

#### Description  
  https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/CustomResource.md#virtualserver-1 lists only `type` and `interval` as required for a health check. But if I specify only those two parameters, the health check is not added to the pool members.

#### Steps To Reproduce
1) Create a VS with only the required health params

```yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: my-new-virtual-server
  namespace: steve-test
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "1.2.3.4"
  pools:
  - path: /
    service: django-psql-example
    servicePort: 8080
    monitor:
      type: http
      interval: 5
```

2) Check the pool members in the web console

![image](https://user-images.githubusercontent.com/24236108/89326188-c5055980-d63e-11ea-9728-d2be6bc76ad3.png)

3) Update the VS to have all health check params

```yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: my-new-virtual-server
  namespace: steve-test
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "142.34.151.117"
  pools:
  - path: /
    service: django-psql-example
    servicePort: 8080
    monitor:
      type: http
      interval: 5
      timeout: 10
      recv: ""
      send: /
```

4) Check the pool members in the web console

![image](https://user-images.githubusercontent.com/24236108/89328405-31ce2300-d642-11ea-81b0-2a195c42e9c4.png)

#### Expected Result 
Health monitor added with default values when using only required parameters.

#### Actual Result
No health check added unless all parameters specified.

#### Diagnostic Information
CIS log with only required params
```
2020/08/04 17:33:25 [INFO] Enqueueing VirtualServer: &{{ } {my-new-virtual-server  steve-test /apis/cis.f5.com/v1/namespaces/steve-test/virtualservers/my-new-virtual-server bdabcd7a-685d-40de-a508-292b1cb3e0a5 14803477 1 2020-08-04 17:33:25 +0000 UTC <nil> <nil> map[f5cr:true] map[] [] []  []} {cafe.example.com 1.2.3.4 [{/ django-psql-example 8080  {http   5 0}}]  }}
```

CIS log with all health check params
```
2020/08/04 18:02:46 [INFO] Enqueueing VirtualServer: &{{ } {my-new-virtual-server  steve-test /apis/cis.f5.com/v1/namespaces/steve-test/virtualservers/my-new-virtual-server bdabcd7a-685d-40de-a508-292b1cb3e0a5 14828089 2 2020-08-04 17:33:25 +0000 UTC <nil> <nil> map[f5cr:true] map[] [] []  []} {cafe.example.com 1.2.3.4 [{/ django-psql-example 8080  {http /  5 10}}]  }}
```

#### Observations (if any)
Not sure if this is a bug in the code, or just the documentation needs to be updated to list all params as required.
