### ISSUE TITLE
clouddocs needs to be updated with "apps/v1" [DOC]

### ISSUE THREAD

**Issue by fchmainy** [F5Networks/k8s-bigip-ctlr#1479]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
examples on clouddocs still have "extensions/v1beta1" for API Version but it has been deprecated and could break deployment. Should be updated to use   "apps/v1".

#### Steps To Reproduce
1) copy/paste examples listed on https://clouddocs.f5.com/containers/latest/userguide/kubernetes/#quickstart

#### Expected Result 
```
apiVersion: apps/v1
kind: Deployment
metadata:
   [...]
spec:
 [...]
  selector:
    matchLabels:
        app:
```

#### Actual Result  
no matches for kind "Deployment" in version "extensions/v1beta1"
plus additional errors (missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec)

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
Jira for PM tracking CONTCNTR-2108

**Comment by mdditt2000** [comment]
Document needs to be 

```
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec: 
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: k8s-bigip-ctlr
```
