### ISSUE TITLE
iRule support for TransportServer CRD

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#1570]
#### Title
iRule support for TransportServer CRD

#### Description
Add support to attach an iRule to a TransportServer CRD.  This could be used for things like proxy protocol or SNI inspection.

#### Actual Problem
Currently you can not use an iRule with a TransportServer

#### Solution Proposed
Add ability to load an iRule.  Either an existing iRule or potentially load from a ConfigMap (?).

#### Alternatives
Currently you would need to do VIP targetting

#### Additional context
This will provide a generic mechanism for attaching proxy protocol iRules to TCP virtual servers that are created using TransportServer

**Comment by mdditt2000** [comment]
@chen23 two iRule Github issues came in at once!

Question - Ok to deliver referencing a iRule in the CRD first as shown below example 1?

**example 1**

```
apiVersion: "cis.f5.com/v1"
kind: CRD
metadata:
  name: my-crd
spec:
  virtualServerAddress: "172.16.3.4"
  iRules:
    - /Common/test-irule.  --------------------- add here!
  selector:
    matchLabels:
      app: nginx
```
Then focus on something like example 2

**example 2**

```
apiVersion: "cis.f5.com/v1"
kind: iRule
metadata:
  name: my-new-irule
  namespace: my-namespace
spec:
  ruleDefinition: |
    when HTTP_REQUEST {
        if { [HTTP::uri] starts_with "/abc/" } {
            HTTP::uri [string map {"/abc/" "/xyz/"} [HTTP::uri]]
        }
    }
```
