### ISSUE TITLE
iRule CRD and allow attaching iRule to Virtual Server Resources

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#1571]
#### Title
iRule CRD and allow attaching iRule to Virtual Servers

#### Description
The ability to create iRules from Kubernetes Custom Resources and attaching those to Virtual Servers.

#### Actual Problem
We have some specific routing logic that the ability to manage these at the k8s layer along with allowing tenants to write their own using custom resources would make it a smooth process.

#### Solution Proposed
Custom Resources for iRules and allow attaching those to Virtual Server Custom Resources.

**Comment by mdditt2000** [comment]
@mitchellmaler Good morning. You looking for something like the following?

```
apiVersion: "cis.f5.com/v1"
kind: CRD
metadata:
  name: my-crd
spec:
  virtualServerAddress: "172.16.3.4"
  iRules:
    - /Common/test-irule.  --------------------- add here!
  selector:
    matchLabels:
      app: nginx
```
If this is what you want i can get this added. Please let me know.
