### ISSUE TITLE
unable to fetch CIS operator from RedHat marketplace in OpenShift 4.6

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#1605]
#### Setup Details
 CIS Version : 2.2.1  
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.2      
 AS3 Version: 3.24
 Agent Mode: AS3      
 Orchestration: OSCP      
 Orchestration Version: 4.6.7 
 Pool Mode: Cluster     
 Additional Setup details: using default CNI 

#### Description  
  
OperatorHub has two entries for CIS.  The "marketplace" fails to load the operator.

#### Steps To Reproduce
1) got to operator hub
2)type 'f5'
3) select 'marketplace' item
![image](https://user-images.githubusercontent.com/63689/101668822-0a87c800-3a1f-11eb-8f63-01658c2758e5.png)

#### Expected Result 
works

#### Actual Result  
does not work

#### Diagnostic Information
```
...
  containerStatuses:
  - image: registry.marketplace.redhat.com/rhm/f5networks/k8s-bigip-ctlr-operator@sha256:e774850d9adf1b7fc49bf1e372c8ba66102457d1f672e95ff181fc7037e3e09d
    imageID: ""
    lastState: {}
    name: f5-bigip-ctlr-operator
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "registry.marketplace.redhat.com/rhm/f5networks/k8s-bigip-ctlr-operator@sha256:e774850d9adf1b7fc49bf1e372c8ba66102457d1f672e95ff181fc7037e3e09d"
        reason: ImagePullBackOff
  hostIP: 10.1.1.9
  phase: Pending
  podIP: 10.131.0.121
  podIPs:
  - ip: 10.131.0.121
  qosClass: BestEffort
  startTime: "2020-12-09T15:35:20Z"
```
