### ISSUE TITLE
Question: How are Virtual Server IP addresses selected?

### ISSUE THREAD

**Issue by Vaccano** [F5Networks/k8s-bigip-ctlr#1729]
When using the F5 BIG-IP Container Ingress Services (CIS), how does it choose the IP address for the Virtual Servers it creates?  Or are those created manually?

I have read the documentation, but I can't seem to find a consistent answer.  It is almost as if there are three different ways it can be setup: ConfigMap, Custom Resources or Routes (the docs seem to indicate that Routes are an OpenShift only option).  Is this correct?  If so, which is the default?

I want to try this out with my F5 BIG-IP, but I need to be sure it will not just take any IP address that it wants.  Hence this question:

**How does the CIS choose the IP addresses for the Virtual Servers?**

**Comment by mdditt2000** [comment]
Good morning @Vaccano 

The Virtual Servers "aka PUBLIC IP" can we assigned manually or by using the new IPAM controller currently in PRE-VIEW. If you are starting out with CIS i would recommend using customer resource definitions. 

Docs - https://clouddocs.f5.com/containers/latest/userguide/crd/
IPAM - https://github.com/f5devcentral/f5-ipam-controller

Here is a guide that i created to help https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.3/ipam
Here are some examples of crds https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/_static/config_examples/crd/basic

Example

```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: my-new-virtual-server
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: caffee.example.com
  virtualServerAddress: "172.16.3.8". ----------------------- Define the Virtual Address here if not using IPAM
  pools:
  - path: /coffee
    service: svc-2
    servicePort: 80
```
Please let me know if you need more information. I am also on slack @mdditt2000
