### ISSUE TITLE
Allow VirtualServer CRD without Pools to enable ssl redirect irule

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#1736]
#### Title
VirtualServer without Pools to enable ssl redirect irule

#### Description
Today we use a redirect irule on our big-ip on all of our virtualserver to make sure https/ssl is forced. This means we duplicate each virtualserver where one is on port 443 that has the referenced pool/polices and one that is on port 80 that just has the irule for the redirect and no pools or polices for routing.

#### Actual Problem
Cannot create VirtualServer without Pools. CIS controller throws error
```
f5-bigip-ctlr-f503-54d995ffd7-87gds f5-bigip-ctlr 2021/03/04 22:55:12 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/PARTITION/Shared/NAME_redirect_80/snat: should NOT have fewer than 1 properties] message:declaration is invalid]
```

#### Solution Proposed
Either allow a VirtualServer to be created without a pool that just provides the IP and iRules

#### Alternatives
Not using CRD mode and use AS3 ConfigMap directly

#### Additional context

example yaml that recieved that error above:

```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: test-redirect
  labels:
    f5cr: "true"
spec:
  virtualServerName: "NAME_redirect"
  virtualServerAddress: "redacted"
  iRules:
    - /Common/SSL_301_Redirect
```
