### ISSUE TITLE
Add support for Firewall Policies in VirtualServer CRD

### ISSUE THREAD

**Issue by mikejoh** [F5Networks/k8s-bigip-ctlr#1740]
#### Title
Add support for Firewall Policies in VirtualServer CRD

#### Description
At the moment there's no way of specifying Firewall Policies (AFM) in the VirtualServer CRD, we've hit a use case where we need to do this in a particular environment. IMHO for this to be feature complete there should at least be a way of specifying Firewall Policy Enforced and Staged, besides these two the Log Profile would also make sense to add at the same time or as part of the work on this feature.

We have built and deployed part of what i've described above, as seen here: https://github.com/mikejoh/k8s-bigip-ctlr/commit/454dfe34cdd8e402d4c93d09f3dc72a4ac1bf7f7. ~~It's basically only support for Firewall Policy Enforced at the moment, this works as far as we've tested.~~

**Update:** We're testing extension of Staged and Log profiles at the moment. Based on the same branch as we've linked to above.

We can provide a PR implementing the extension of Firewall Policies and Log Profile to the VirtualServer CRD in the coming week.

#### Actual Problem
In one of our environments we have AFM enabled which in our case by default denies all traffic. When we're about to launch new services we need to specify an enforced Firewall Policy allowing traffic to the Virtual Servers we create.

#### Solution Proposed
Extended the VirtualServer CRD with:
* Firewall Policy Enforced
* Firewall Policy Staged
* Log Profile

#### Alternatives
N/A

#### Additional context
We've seen that there's a need of support configurable profiles of other types, e.g. OneConnect (#1735). The question is if there's a plan of supporting a way of specifying multiple profiles/policies as described in the OneConnect issue or just extending the VirtualServer CRD with new fields, one per profile/policy.

**Comment by mdditt2000** [comment]
thanks @mikejoh for opening this. I am going to start drafting some requirements for a possible security CRD. Plan would be to extending the VirtualServer CRD with new fields, one per profile/policy.

**Comment by mdditt2000** [comment]
@mikejoh are you using AS3 to post your firewall policies (AFM) to BIG-IP?

**Comment by mikejoh** [comment]
> thanks @mikejoh for opening this. I am going to start drafting some requirements for a possible security CRD. Plan would be to extending the VirtualServer CRD with new fields, one per profile/policy.

Great!

> @mikejoh are you using AS3 to post your firewall policies (AFM) to BIG-IP?

In this case no, we've created what we need manually at the moment.

**Comment by mikejoh** [comment]
@mdditt2000 Hi! Have you made any progress in regards to this issue?

**Comment by mdditt2000** [comment]
@klippo coming in an upcoming release with the introduction of policy CRD. This is what we are thinking 

```
 l3Policies:
                  type: object
                  properties:
                    dos:
                      type: string
                      pattern: '^\/([A-z0-9-_+]+\/)+([A-z0-9]+\/?)*$'
                    firewall:
                      type: string
                      pattern: '^\/([A-z0-9-_+]+\/)+([A-z0-9]+\/?)*$'
```

allow-list/deny-list. Here is the proposed schema. 

https://github.com/F5Networks/k8s-bigip-ctlr/blob/policy_crd/docs/config_examples/crd/Policy/policy-crd.yaml

Let me know your thoughts?

**Comment by mdditt2000** [comment]
This is resolved in CIS 2.7. Please look at the following example

```
spec:
  l7Policies:
    waf: /Common/WAF_Policy
  l3Policies:
    firewallPolicy: /Common/WEB_Policy
  profiles:
    http: /Common/Custom_HTTP
    logProfiles:
      - /Common/Log all requests
```

https://github.com/mdditt2000/kubernetes-1-19/blob/master/cis%202.7/policy/crd/policy-crd.yaml

Closing issue
