### ISSUE TITLE
/metrics endpoint is not served when CIS runs with “--custom-resource-mode=true” 

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#1873]
#### Setup Details
 CIS Version : 2.4.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.0.1.1     
 AS3 Version: 3.25
 Agent Mode: AS3       
 Orchestration: K8S (AKS)     
 Orchestration Version:       
 Pool Mode: Cluster    
 Additional Setup details: AKS cluster

#### Description  
 
CIS should serve metrics at 0.0.0.0:8080/metrics but this is not available when CIS is deployed with config param ```  “--custom-resource-mode=true” ```. If you try to hit this endpoint in CRD mode, you get a 404 Not Found error. This is true even from executing curl locally on the CIS container with ```curl -v http://localhost:8080/metrics```

I don't believe this parameter should be related to whether or not metrics are available from CIS. 

The health endpoint at 0.0.0.0:8080/health is still available and serves a 200 OK.

#### Steps To Reproduce
1) Deploy CIS in CRD mode. Example deployment below
2) From CIS pod, or from another pod, curl http://<cis_pod_ip>:8080/metrics and receive 404 Not Found

#### Expected Result 
Expect to get metrics of CIS

#### Actual Result  
Get 404 Not found 

#### Diagnostic Information

````yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5cis2
  namespace: kube-system
spec:
# DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-deployment
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        seccomp.security.alpha.kubernetes.io/defaultProfileName: unconfined
        seccomp.security.alpha.kubernetes.io/pod: unconfined
      labels:
        app: k8s-bigip-ctlr-deployment
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.4.1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                # Replace with the name of the Secret containing your login
                # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                # Replace with the name of the Secret containing your login
                # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.0.1.5",
            "--bigip-partition=kubernetes",
            "--pool-member-type=cluster",
            "--insecure",
            "--custom-resource-mode=true"
            # for secure communication provide the internal ca certificates using config-map with below option and remove insecure parameter
            #"--trusted-certs-cfgmap=<namespace/configmap>",
            ]
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr
      imagePullSecrets:
        # Secret that gives access to a private docker registry
        #- name: f5-docker-images
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login
````

#### Observations (if any)
1) Even with --log-level=DEBUG I cannot find the reason for this so thanks for investigating.
2) Adding the configuration parameter of "--http-listen-address=0.0.0.0:8080" does not seem to help.
