### ISSUE TITLE
Unable to upgrade from 2.2.0 (or below) to 2.2.1 (or above)

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#1888]
#### Setup Details
 CIS Version : 1.14      
 Build: f5networks/k8s-bigip-ctlr:1.14.0       
 BIGIP Version: Big IP 15.1      
 AS3 Version: 3.28      
 Agent Mode: CCCL       
 Orchestration: K8S
 Orchestration Version:  1.20.8
[pod.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778363/pod.yml.txt)
[ns.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778364/ns.yml.txt)
[ingress.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778365/ingress.yml.txt)
[ctlr.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778366/ctlr.yml.txt)
[svc.yml.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778367/svc.yml.txt)

 Pool Mode: Cluster      
 Additional Setup details: Flannel/ 1 master-2nodes

#### Description  
  I am trying to upgrade from 2.2.0. to 2.2.1 (same behavior from 1.14.0 to 2.4.1) 
  I created 15 namespaces, 10 services, 2 pods per service and 150 ingresses.
  After the upgrade to I cannot make any changes. The K8s changes do not reflect on the BIGIP.

#### Steps To Reproduce
1) I have included the manifest for pods/services/ns/ingress and the controller. 
2) Deploy them with version 2.2.0
3) Upgrade to 2.2.1
4) Scale up a replicaset  "kubectl scale rc nginx --replicas=3 -n ns9"

#### Expected Result 
The pools members are not reflected

#### Actual Result  
Pool members should become 3

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by skenderidis** [comment]
Please find the logs not-working.txt from the controller. The pods added, have IPs 10.244.2.36 and 10.244.2.35 
Please also find a working config (on version 2.2.0) . the pods added have IPs. 10.244.1.31, 10.244.1.32. and 10.244.2.38
[not-working.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778435/not-working.txt)
[working.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6778436/working.txt)

**Comment by trinaths** [comment]
When you scale to 3 replicas, can you share the below info. For CIS 2.2.1 and above.
```
$> kubectl get svc,ep,rc,ing --all-namespaces

```

**Comment by skenderidis** [comment]
If you change the --log-level to INFO or Criticial on the controller configuration, the issue doesn't appear
The issue appears only if you have log-level to DEBUG

**Comment by trinaths** [comment]
Thanks @skenderidis  for the update. Created CONTCNTR-2779 to further investigate this issue.

**Comment by mdditt2000** [comment]
Good morning @skenderidis I am looking into this issue. Is there a reason why you are still using "--agent=cccl" API?

**Comment by mdditt2000** [comment]
@skenderidis something is not correct with your CIS deployment manifest

```
[kube@k8s-1-19-master 1888]$ kubectl get deployment -n kube-system
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
coredns                     2/2     2            2           335d
k8s-bigip-ctlr-deployment   0/1     0            0           2m15s
```
Moving to know working manifest

https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.5/github/1888

**Comment by mdditt2000** [comment]
Recreate --

No namespaces defined. CIS monitors all namespaces for Ingress and creates the virtuals,pools etc. All pools are green

```
      containers: 
        - 
          args: 
            - "--bigip-username=$(BIGIP_USERNAME)"
            - "--bigip-password=$(BIGIP_PASSWORD)"
            - "--bigip-url=192.168.200.60"
            - "--bigip-partition=k8s"
            - "--pool-member-type=cluster"
            - "--flannel-name=fl-vxlan"
            - "--log-level=DEBUG"
            - "--agent=cccl"
          command: 
            - /app/bin/k8s-bigip-ctlr
          env: 
            - 
              name: BIGIP_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: bigip-login
            - 
              name: BIGIP_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: bigip-login
          image: "f5networks/k8s-bigip-ctlr:2.2.0"
```

Moving to CIS 2.2.1

**Comment by mdditt2000** [comment]
Can reproduce the issue 

ingress.extensions/ing10-svc10-ns15 configured
ingress.extensions/ing10-svc10-ns16 created. --- This doesn't get created on BIG-IP. 

Going to try re-install CIS 2.2.1 to see if the Ingress is created.

**Comment by mdditt2000** [comment]
After moving to CIS 2.2.1 i DO NOT see the additional ns, ingress, pod and service

Added
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns16
---
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: ns16
spec:
  replicas: 2 
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
---
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: ing10-svc10-ns16
  namespace: ns16
  annotations:
     ingress.kubernetes.io/allow-http: "true"
     kubernetes.io/ingress.class: f5
     'virtual-server.f5.com/ip': "10.169.213.246" 
     virtual-server.f5.com/health: |
      [
        {
          "path":     "www.ing10-svc10-ns16.com/",
          "send":     "GET / HTTP/1.1\r\nHost: www.ing10-svc10-ns16.com\r\nConnection: Close\r\n\r\n",
          "interval": 5,
          "timeout":  10
        }
      ]
spec:
  rules:
   - host: www.ing10-svc10-ns16.com 
     http:
       paths:
       - path: /
         backend:
            serviceName: svc10-ns16
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: svc10-ns16
  name: svc10-ns16
  namespace: ns16
spec:
  ports:
    # The port that this service should serve on.
    - port: 80
  selector:
    app: nginx
  type: ClusterIP
---
```

https://github.com/mdditt2000/kubernetes-1-19/tree/master/cis%202.5/github/1888

Can see CIS is logging  the ingress but not on BIG-IP

```
2021/08/11 20:17:58 [DEBUG] [CORE] Configured rule: {ingress_www.ing10-svc10-ns16.com__ingress_ns16_svc10-ns16 www.ing10-svc10-ns16.com/ 0 [0xc000984840] [0xc00097e980]}
```

https://raw.githubusercontent.com/mdditt2000/kubernetes-1-19/master/cis%202.5/github/1888/k8s-log.log

@trinaths i can reproduce this issue. Can we review after standby
