### ISSUE TITLE
can not delete virtual server automatically After the delete ingress operation is executed

### ISSUE THREAD

**Issue by guardian0916** [F5Networks/k8s-bigip-ctlr#2011]
Bigip can not delete virtual server automatically after the delete ingress operation is executed

####Setup Details
CIS Version : 2.3.0
Build: f5networks/k8s-bigip-ctlr:2.3.0
BIGIP Version: BIG-IP 15.1.3.1 Build 0.0.18 Point Release 1
AS3 Version:3.25.0
Agent Mode: Custom Resource Definitions
Orchestration: K8S
Pool Mode: Cluster

#### Description
after executing command: kubectl create -f f5-l7-host-f5cis.yaml  ,the partition named K8S of Bigip can automatically create virtual server 、poliycy、pool.and the f5-l7-host-f5cis.yaml is:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ing23
  namespace: f5cis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ing23
  template:
    metadata:
      labels:
        app: nginx-ing23
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-ing23
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ing23-2
  namespace: f5cis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ing23-2
  template:
    metadata:
      labels:
        app: nginx-ing23-2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-ing23-2
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ing23
  name: svc23
  namespace: f5cis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ing23
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ing23-2
  name: svc23-2
  namespace: f5cis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ing23-2
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: l7vs-ingress
  namespace: f5cis
  annotations:
    #kubernetes.io/ingress.class: "F5"
    virtual-server.f5.com/ip: "192.168.21.236"
    virtual-server.f5.com/partition: "K8S"
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/balance: "round-robin"
spec:
  rules:
  - host: www.test1.com
    http:
      paths:
      - backend:
          serviceName: svc23
          servicePort: 80
        path: /
  - host: www.test2.com
    http:
      paths:
      - backend:
          serviceName: svc23-2
          servicePort: 80
        path: /

```

but after executing command: kubectl create -f f5-l7-host-f5cis.yaml  ,the partition named K8S of Bigip can automatically delete poliycy、pool、node,except the virtual server.

###roubleshooting steps

1. the f5cis.yaml is:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment-b-f5cis
  namespace: kube-system
spec:
  # DO NOT INCREASE REPLICA COUNT
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.3.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            # See the k8s-bigip-ctlr documentation for information about
            # all config options
            # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=192.168.21.232",
            "--bigip-partition=K8S",
            "--pool-member-type=cluster",
            "--insecure=true",
            "--namespace-label=f5cis=enable"
            ]
      imagePullSecrets:
        # Secret that gives access to a private docker registry
        #- name: f5-docker-images
        # Secret containing the BIG-IP system login credentials
        - name: bigip-logi
```n

2. after executing command: kubectl create -f f5-l7-host-f5cis.yaml,view the log of cis.
```
[root@k8s-master01 f5_yaml]# kubectl logs k8s-bigip-ctlr-deployment-b-f5cis-d9f9587cd-dts4z -n kube-system
2021/09/28 09:21:40 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey}' with port '#{sKey.ServicePort}'
2021/09/28 09:21:40 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey}' with port '#{sKey.ServicePort}'
2021/09/28 09:21:40 [ERROR] [Core]Endpoints could not be fetched for service '#{svcKey}' with port '#{sKey.ServicePort}'

```

3. after executing command: kubectl delete -f f5-l7-host-f5cis.yaml,view the log of cis.
```
2021/09/28 09:22:10 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:svc23 ServicePort:80 Namespace:f5cis} and resource ingress_192-168-21-236_80
2021/09/28 09:22:11 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:svc23-2 ServicePort:80 Namespace:f5cis} and resource ingress_192-168-21-236_80
2021/09/28 09:22:18 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:svc23 ServicePort:80 Namespace:f5cis} and resource ingress_192-168-21-236_80
2021/09/28 09:22:20 [WARNING] [CORE] Overwriting existing entry for backend {ServiceName:svc23-2 ServicePort:80 Namespace:f5cis} and resource ingress_192-168-21-236_80
2021/09/28 09:24:44 [INFO] [CORE] Port '80' for service 'svc23' was not found.
2021/09/28 09:24:44 [INFO] [CORE] Service 'svc23' has not been found.
2021/09/28 09:24:44 [INFO] [CORE] Port '80' for service 'svc23-2' was not found.
2021/09/28 09:24:44 [INFO] [CORE] Service 'svc23-2' has not been found.

```
###Expected Result
Can delete virtualServer after executing command: kubectl delete -f f5-l7-host-f5cis.yaml

###Actual Result
Can delete virtualServer after executing command: kubectl delete -f f5-l7-host-f5cis.yaml
Question: How to  delete virtualServer after executing command: kubectl delete -f f5-l7-host-f5cis.yaml?
