### ISSUE TITLE
panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by fabriziofiorucci** [F5Networks/k8s-bigip-ctlr#2016]
#### Setup Details
 CIS Version : 2.5.1 and 2.5.0 crash. CIS version 2.4.1 works fine
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.1.4      
 AS3 Version: 3.31.0-6    
 Agent Mode: AS3       
 Orchestration: OpenShift
 Orchestration Version: 4.7.36
 Pool Mode: Nodeport      
 Additional Setup details: CIS managing OpenShift routes

#### Description  
The bigip-ctlr pod starts correctly, creates all objects on LTM and after a while segfaults logging an "invalid memory address or nil pointer dereference"

#### Steps To Reproduce
Run the helm chart using:

```
 bigip_login_secret: bigip-login
 rbac:
   create: true
 serviceAccount:
   # Specifies whether a service account should be created
   create: true
   # The name of the service account to use.
   # If not set and create is true, a name is generated using the fullname template
   name: k8s-bigip-ctlr
 # This namespace is where the Controller lives;
 namespace: kube-system
 args:
   agent: as3
   log_level: debug
   as3_validation: true
   manage_configmaps: true
   manage_routes: true
   manage_ingress: false
   share-nodes: true
   route_vserver_addr: 1.2.3.4
   # See https://clouddocs.f5.com/containers/latest/userguide/config-parameters.html
   # NOTE: helm has difficulty with values using `-`; `_` are used for naming
   # and are replaced with `-` during rendering.
   # REQUIRED Params
   bigip_url: 172.20.194.111
   bigip_partition: cis
   # OPTIONAL PARAMS -- uncomment and provide values for those you wish to use.
   # verify_interval:
   # node-poll_interval:
   # log_level:
   # python_basedir: ~
   # VXLAN
   # openshift_sdn_name:
   # flannel_name:
   # KUBERNETES
   # default_ingress_ip:
   # kubeconfig:
   # namespace:
   # namespace_label:
   # node_label_selector:
   pool_member_type: nodeport
   insecure: true
   # resolve_ingress_names:
   # running_in_cluster:
   # use_node_internal:
   # use_secrets:
   # custom-resource-mode: true
   log-as3-response: true
   disable-teems: true
 image:
   # Use the tag to target a specific version of the Controller
   user: f5networks
   repo: k8s-bigip-ctlr
   pullPolicy: Always
 resources: {}
   # If you want to specify resources, uncomment the following
   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   # limits:
   #  cpu: 100m
   #  memory: 128Mi
   # requests:
   #  cpu: 100m
   #  memory: 128Mi
 version: latest
```

#### Expected Result 
bigip-ctrl should not crash

#### Diagnostic Information
```
E0930 08:42:38.763881       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 163 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x193d240, 0x28a98f0)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x193d240, 0x28a98f0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).getSecretServiceQueueKeyForIngress(0xc00051c2c0, 0xc00d080140, 0x1b6182f, 0x7, 0xc0005f88e0)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:192 +0x75
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).checkValidSecrets(0xc00051c2c0, 0x1b3f1a0, 0xc00d080140, 0xc0006b5df0, 0xc0006b5d40, 0x3, 0x0)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/validateResources.go:277 +0xe5
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).enqueueSecrets(0xc00051c2c0, 0x1b3f1a0, 0xc00d080140, 0x1b60c62, 0x6)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:827 +0x46
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).newAppInformer.func14(0x1b3f1a0, 0xc00d080140)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:752 +0x53
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006a7f60)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006b5f60, 0x1d507e0, 0xc0006b0420, 0x18fd101, 0xc0006ae360)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a7f60, 0x3b9aca00, 0x0, 0x1, 0xc0006ae360)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000312980)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000250920, 0xc00023e540)
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
```

#### Observations (if any)
This happens using  k8s-bigip-ctlr 2.5.1 and 2.5.0.

Apparently 2.4.1 works just fine

**Comment by trinaths** [comment]
@fabriziofiorucci - Please share the Route examples to reproduce this issue. can you validate this issue with build quay.io/f5networks/k8s-bigip-ctlr-devel:6c746263d946935a69258fc10b9e6c5e530b11fb

**Comment by fabriziofiorucci** [comment]
Thank you @trinaths, a sample route is

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx-unprivileged
  name: nginx-unprivileged
  namespace: testf5
spec:
  host: nginx-api.xyz.tld
  port:
    targetPort: 80-8080
  to:
    kind: Service
    name: nginx-unprivileged
    weight: 100
  wildcardPolicy: None
```

and the service is

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-unprivileged
  name: nginx-unprivileged
  namespace: testf5
spec:
  clusterIP: 172.30.252.79
  clusterIPs:
  - 172.30.252.79
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-8080
    nodePort: 30618
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-unprivileged
  sessionAffinity: None
  type: LoadBalancer
```
