### ISSUE TITLE
Changes on Ingress Resource Service Port not reflected on BIGIP

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2030]
#### Setup Details
 CIS Version : 2.5.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 14.1     
 AS3 Version: 3.28      
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version: 1.20       
 Pool Mode: Cluster      
 Additional Setup details: CNI Flannel

#### Description  
When you create an ingress resource with the wrong service port number and then you change it to the correct one, the changes are not reflected on BIGIP.  
You have to delete and re-apply the ingress resource in order for the changes to be reflected

#### Steps To Reproduce
1) Create service running on port 80

2) Create an Ingress resource pointing to the service but on a wrong port

3) Review that F5 has a virtual server created but 0 members assigned to the pool.

4) Correct the Ingress resource service port. 

5) No change on F5. 

#### Expected Result 

The expected result is to change the pool members to reflect the correct port. 

#### Observations (if any)

Looking at the CIS logs I can see that CIS still looks at the wrong Port even after it has been changed.
 
#### Configuration

Initial Config.

---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  selector:
    matchLabels:
      app: payments
  replicas: 2
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: f5devcentral/f5-demo-httpd
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pay
  labels:
    app: svc-pay
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: payments

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-ingress
  annotations:
    virtual-server.f5.com/ip: "192.168.4.201"
spec:
  ingressClassName: f5
  rules:
  - host: app1.f5demo.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-pay
            port:
              number: 555

```

####### After the above is applied. change the Service Port Number to 8080. ##########

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-ingress
  annotations:
    virtual-server.f5.com/ip: "192.168.4.201"
spec:
  ingressClassName: f5
  rules:
  - host: app1.f5demo.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-pay
            port:
              number: 8080

```
