### ISSUE TITLE
Same host *.example.com is configured with different VirtualServerAddress

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/k8s-bigip-ctlr#2206]
#### Setup Details
 CIS Version : 2.7.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP BIG-IP 15.1.2 Build 0.0.9 Final
 AS3 Version: BIG-IP 15.1.2 Build 0.0.9 Final
 Agent Mode: AS3  
 Orchestration: K8S
 Orchestration Version: v1.21.6
 Pool Mode: Nodeport      

#### Description  
Create two VirtualServers with a different address but sharing the same wildcard domain hostname. 
The controller throws an error "Same host *.example.com is configured with different VirtualServerAddress"

#### Steps To Reproduce
1) Create two VirtualServers with the same Host such as *.example.com but a different IP
2) Create the TLS Profile shared by both using the same *.example.com in the hosts property
3)

#### Expected Result 
Both VirtualServers are created on the device with the same *.example.com policy but different IP.

#### Actual Result  
CIS throws an error processing those VirtualServer resources

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment]
@mitchellmaler please share example CRDs to validate and further investigate this issue.

**Comment by trinaths** [comment]
@mitchellmaler please share example CRDs to validate and further investigate this issue.

**Comment by mitchellmaler** [comment]
Hi @trinaths sorry for the delay. Here are two example VirtualServers that share the same domain but have a different IP. 
On 2.6 we did not have to set the hostnames on the vs or tls policy but found out that was a requirement when upgrading to 2.7. Using these same VirtualServers (and the tls profile they share) I set the host to *.example.com but it complained they cannot be the same.

```yaml
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  annotations:
    domian: example.com
  labels:
    app.kubernetes.io/managed-by: pulumi
    f5cr: "true"
  name: example-internal-https
  namespace: istio-system
spec:
  httpTraffic: allow
  iRules:
  - /Common/SSL_308_Redirect
  - /Common/X-Forwarded-Proto
  - /Common/X-Request-Start
  - /Common/X-Forwarded-For
  - /Common/Strip-Server-Name
  - /Common/Strict-Transport-Security
  pools:
  - monitor:
      interval: 3
      send: "GET / HTTP/1.1\r\nHost: \r\nConnection: Close\r\n\r\n"
      timeout: 5
      type: http
    path: /
    service: istio-ingressgateway-internal
    servicePort: 443
  tlsProfileName: example-tls-profile
  virtualServerAddress: 10.182.221.51
  virtualServerName: example-internal-https

apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  annotations:
    domian: example.com
  labels:
    app.kubernetes.io/managed-by: pulumi
    f5cr: "true"
  name: example-external-https
  namespace: istio-system
spec:
  httpTraffic: allow
  iRules:
  - /Common/SSL_308_Redirect
  - /Common/X-Forwarded-Proto
  - /Common/X-Request-Start
  - /Common/X-Forwarded-For
  - /Common/Strip-Server-Name
  - /Common/Strict-Transport-Security
  pools:
  - monitor:
      interval: 3
      send: "GET / HTTP/1.1\r\nHost: \r\nConnection: Close\r\n\r\n"
      timeout: 5
      type: http
    path: /
    service: istio-ingressgateway-external
    servicePort: 443
  tlsProfileName: example-tls-profile
  virtualServerAddress: 10.182.221.50
  virtualServerName: example-external-https
```
