### ISSUE TITLE
ExternalDNS still adding multiple VIPs with same IP, different port to GTM pool

### ISSUE THREAD

**Issue by mikeoleary** [F5Networks/k8s-bigip-ctlr#2212]
#### Setup Details
 CIS Version : 2.7.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.0      
 AS3 Version: 3.25     
 Agent Mode: AS3   
 Orchestration: K8S/OSCP      
 Orchestration Version:       Azure Kubernetes Service
 Pool Mode: Cluster
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
This issue appears to be related to an earlier issue [#1918](https://github.com/f5networks/k8s-bigip-ctlr/issues/1918)

However, I think the previous fix mentioned in 2.7.1 release notes only fixes when you use **httpTraffic: redirect.** In my case, I am using **"httpTraffic: allow"** and I can still reproduce this problem. 

When I create a CRD of type VirtualServer, I use **httpTraffic: allow** and, as designed, 2x VS's are created on BIG-IP. 1 on port 80, the other on 443. However, BOTH of these VS's are added to the WideIP when I create an ExternalDNS crd. This is not ideal.

#### Steps To Reproduce
1) Create CRD of type VirtualServer with httpTraffic: allow
2) Create CRD of type ExternalDNS
3) Take note of the pool members in the GTM config on BIG-IP

#### Expected Result 

1 GTM pool member for each VS CRD.

#### Actual Result  

2 GTM pool members for the 1 VS CRD.
#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```

**Comment by trinaths** [comment]
@mikeoleary please share the CRD manifest you are trying.

**Comment by trinaths** [comment]
Created CONTCNTR-3140 for internal tracking.

**Comment by mikeoleary** [comment]
@trinaths my CRD's below.

````yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: hello-world-virtual-server
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: demo.my-f5.com
  tlsProfileName: hello-world-tls  # --> This will attach hello-world-tls TLSProfile
  virtualServerAddress: "10.0.2.100"
  virtualServerName: "hello-world-vs"
  httpTraffic: allow
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 80
    monitor:
      type: http
      interval: 10
      timeout: 31
      send: "/"
      recv: ""
````

and 

````yaml
apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-demo
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  domainName: demo.my-f5.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  #- name: demo.my-f5.com
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/GSLBServer1
    monitor:
      type: http
      send: "GET / HTTP/1.1\r\nHost: demo.my-f5.com\r\n"
      recv: ""
      interval: 10
      timeout: 10
````
