### ISSUE TITLE
Set up docs deployment to s3

### ISSUE THREAD

**Issue by jputrino** [F5Networks/k8s-bigip-ctlr#224]
The travis configs for doc deployment need to be added for this project.

- [x] add the [deploy-docs](https://github.com/F5Networks/f5-ci-docs/blob/master/scripts/deploy-docs.sh) script
- [x] add the deployment (one for each release branch):
   
```
deploy:
- provider: script
  skip_cleanup: true
  on:
    branch: v1.0-stable
    repo: F5Networks/k8s-bigip-ctlr
  script:
  - ./scripts/deploy-docs.sh publish-product-docs-to-prod connectors/k8s-bigip-ctlr v1.0
```
- [x] add the AWS credentials to travis-ci for this repo (requires assistance from @swormke)
