### ISSUE TITLE
MultiHost VS & policy CRD profiles attached via LTM policy and not assigned globally

### ISSUE THREAD

**Issue by de1chk1nd** [F5Networks/k8s-bigip-ctlr#2251]
#### Title
MultiHost VS & policy CRD profiles attached via LTM policy and not assigned globally

#### Description
When I create two VS CRs with Host Group and policy CRD, policy CRD seems to be global (attached to VS - not FQDN).

I have VS 1 and VS 2 - VS 1 gets a WAF policy assigned - I do not want to assaign a WAF policy to VS 2.

**Virtual Server No° 1:**
```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: custtech-virtual-server
  labels:
    f5cr: "true"
spec:
  host: '*.k8s.lab.bigip'
  hostGroup: "echo-app"
  virtualServerAddress: "10.1.10.202"
  policyName: custtech-policy
  pools:
  - path: /
    service: echo-app
    servicePort: 80
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10

```
**Virtual Server No° 2:**
```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: custtech-virtual-server-dev
  labels:
    f5cr: "true"
spec:
  host: echo-dev.k8s.lab.bigip
  hostGroup: "echo-app"
  virtualServerAddress: "10.1.10.202"
  pools:
  - path: /
    service: webapp-v2
    servicePort: 80
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10

```
#### Actual Problem
I'm not able to control the assigned policies on FWDN level - only on IP/Virtual Server level

#### Solution Proposed
Assign / un-assaing polices on FQDN level (I do not know if it is possible for all profiles - but for the majority it should be... and for WAF policy it is possible.

#### Alternatives
I checkd the behavior for WAF policy assignent via "WAF:" statement - same result. it is still assaigned on IP/Virtual Server level.

#### Additional context
n/a

**Comment by trinaths** [comment]
Since Policy CRD is designed to be global, suggest using https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/config_examples/customResource/VirtualServer/waf to add WAF to Virtual.

https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/VirtualServer/waf/vs-with-waf.yaml#L12

**Comment by trinaths** [comment]
Created [CONTCNTR-3173] for internal tracking.

**Comment by de1chk1nd** [comment]
Hi,

thx for the update. A few remarks:

1. I did the test as you suggested - same result (see declaration below - only the first "WAF_policy" was assigned as default)

2. Since multiHost CRD, we  went from "global" to more local. It would be great, if policy CRD cann allign to it, too. At least have the option to assign different WAF policies to specific FQDNs (or disable WAF for certain FQDNS)

3. I see some synergies with other tools like having external CIS - allow flexible handling of WAF policies, timeouts, persistence (2.8 CIS)... and maybe an internal ingress controller like NGINX KIC for a more granualr handling/routing

---

```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: custtech-virtual-server
  labels:
    f5cr: "true"
spec:
  host: '*.k8s.lab.bigip'
  hostGroup: "echo-app"
  waf: "/Common/WAF_policy"
  virtualServerAddress: "10.1.10.202"
  pools:
  - path: /
    service: echo-app
    servicePort: 80
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
```


```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: custtech-virtual-server-dev
  labels:
    f5cr: "true"
spec:
  host: echo-dev.k8s.lab.bigip
  hostGroup: "echo-app"
  virtualServerAddress: "10.1.10.202"
  waf: "/Common/WAF_policy_2"
  pools:
  - path: /
    service: webapp-v2
    servicePort: 80
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
```
