### ISSUE TITLE
Not consistent configuration between Ingress and CRDs on Pool member discovery

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2253]
#### Setup Details
 CIS Version : 2.7.1     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1

#### Description  
When deploying the same service through Ingress and CRDs the configuration for Service Port is different. 
When CIS is configured in CRD mode it looks for the TargetPort and when it is on Ingress mode it looks for the service Port. This is creating confusion.   

#### Steps To Reproduce
1) create the following Deployment and Service 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app1
```  
2) Create an Ingress with ServicePort 8080 it will not discover any members

```  
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cis-fanout
  annotations:
    virtual-server.f5.com/ip: "10.1.10.50"
spec:
  ingressClassName: f5
  rules:
  - host: fanout.f5demo.local
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-svc
            port:
              number: 8080
```  

![image](https://user-images.githubusercontent.com/11005568/155529959-c75a9c80-392b-4854-bb8a-e2ec832e22cd.png)

3) Create an Ingress with ServicePort 80 it will not discover any members

```  
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-svc
            port:
              number: 80
```  

![image](https://user-images.githubusercontent.com/11005568/155530584-23d837bc-37f3-4dc1-9876-702e5ecb818d.png)

4) The opposite applies with CRD. CRD will work with 8080 but not with 80.
below find the example for Port 80 that doesn't work
```  
apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: my-transport-server
spec:
  virtualServerAddress: "10.1.10.50"
  virtualServerPort: 80
  mode: standard
  snat: auto
  pool:
    service: myapp-svc
    servicePort: 80
```  
![image](https://user-images.githubusercontent.com/11005568/155531015-2040a3da-b58b-4acc-99d7-5532cf08c20b.png)

#### Expected Result 
CIS should discover services with the same way on both Ingress and CRD mode
