### ISSUE TITLE
EDNS doesn't work when VS CRD is using "virtualServerName" parameter

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2335]
#### Setup Details
 CIS Version : 2.8.0  
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.30      
 Agent Mode: AS3       
 Orchestration: K8S      
 Orchestration Version:       

#### Description  
EDNS doesn't discover services when VS CRD is using parameter virtualServerName. EDNS pool is created but with 0 members  

![image](https://user-images.githubusercontent.com/11005568/161411172-ece90a04-bdd1-434f-ab64-bc3e1ecf1685.png)

#### Steps To Reproduce
1) Create a VS CRD
```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: single-pool-vs
  labels:
    f5cr: "true"
spec:
  host: app1.f5demo.local
  virtualServerName: "single-pool-vs"
  virtualServerAddress: "192.168.4.55"
  pools:
  - path: /
    service: echo-svc
    servicePort: 80
```
2) Create a EDNS CRD
```
apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  labels:
    f5cr: "true"
spec:
  domainName: app1.f5demo.local
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/self
```

**Comment by trinaths** [comment]
Created CONTCNTR-3269 for internal tracking.

**Comment by lavanya-f5** [comment]
@skenderidis  Tried reproducing the issue with 2.9 build in local env. In my case pool members are being added properly. 

<img width="1409" alt="Screenshot 2022-06-22 at 2 50 36 PM" src="https://user-images.githubusercontent.com/65212197/174993800-a0c41344-509d-475d-b124-32d3c8ec0354.png">

vs definition
```
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: cr-vs-foo-cr-edns-svc-foo
  namespace: default
spec:
  allowVlans: []
  host: foo.com
  httpTraffic: allow
  iRules: []
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /foo
    service: cr-edns-svc-foo
    servicePort: 80
  snat: auto
  tlsProfileName: cr-tls-foo-cr-edns-svc-foo
  virtualServerAddress: 10.x.x.x
  virtualServerName: single-pool-vs
```

Could you please provide cis logs to debug this issue further
