### ISSUE TITLE
CIS 2.8.0 frequently and abnormally restarts and high memory usage

### ISSUE THREAD

**Issue by kkfinkkfin** [F5Networks/k8s-bigip-ctlr#2353]
#### Setup Details
 CIS Version : 2.8.0      
 BIGIP Version: Big IP 14.1.4        
 Agent Mode: CCCL       
 Orchestration: K8S      
 Orchestration Version: kubernetes 1.17.4      
 Pool Mode: Cluster      
 Additional Setup details: flannel cni
the VE  has 1271 VS

#### Description  
CIS 2.8.0 frequently restarts abnormally with suspected memory leak

#### Steps To Reproduce
1) CIS 2.8.0 running as long time with CCCL mode
2) Observe monitoring （ memory ）and logs

#### Expected Result 
Non-operational abnormal restart

#### Diagnostic Information
CIS  yaml 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: cc-k8s-to-bigip1
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr
    spec:
      containers:
      - args:
        - --bigip-username=admin
        - --bigip-password=admin.F5demo.com
        - --bigip-url=https://10.1.20.252
        - --bigip-partition=p1
        - --pool-member-type=cluster
        - --flannel-name=/Common/flannel_vxlan
        - --insecure=true
        - --log-level=INFO
        - --agent=cccl
        - --manage-ingress=false
        - --namespace=default
        - --disable-teems=true
        - --node-poll-interval=1000
        - --verify-interval=1000
        command:
        - /app/bin/k8s-bigip-ctlr
        image: f5networks/k8s-bigip-ctlr:2.8.0
        name: k8s-bigip-ctlr
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr

``` 

#### Observations
Run 6 days restart 17 times
 ![restart](https://user-images.githubusercontent.com/59547386/162568083-eafd3211-5feb-42bb-9b6a-80502b9409d5.png)

the cis logs
![unexpectd-error](https://user-images.githubusercontent.com/59547386/162568132-5e93d709-a656-4d6c-a921-b043d628d69d.jpeg)
![config](https://user-images.githubusercontent.com/59547386/162568158-32f72a2c-bebb-492f-b205-6e9c513a4b5d.png)

cis monitor, and it's memory usage more than 24G
![memory](https://user-images.githubusercontent.com/59547386/162568172-0abae2a2-1eaa-48cd-b21b-1e4ef7414c58.jpeg)
