### ISSUE TITLE
Openshift SDN integration fails in VxLan manager

### ISSUE THREAD

**Issue by bukovjanmic** [F5Networks/k8s-bigip-ctlr#2375]
#### Setup Details
 CIS Version : 2.8.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: 15.1.2
 AS3 Version: Big IP 3.32.0-4
 Agent Mode: AS3       
 Orchestration: OSCP      
 Orchestration Version: 4.9.24
 Pool Mode: Cluster
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
When creating VirtualServers or TransportServers, VxLan integration does not seem to work.

In operator logs, we see error messages:

2022/04/25 15:30:30 [ERROR] [VxLAN] Vxlan manager could not get VtepMac for 10.130.5.63's node.

looking at the source code, it seems the VxLAN manager is looking for flannel.alpha.coreos.com/public-ip annotation in node where the pod is running.

Howerer, no such annotation is present on the nodes, as we run openshift sdn in networkpolicy mode.

Our setup:

```yaml
apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  annotations:
    operator-sdk/primary-resource: kube-system/f5-server-f5-bigip-ctlr
    operator-sdk/primary-resource-type: Deployment.apps
  name: f5-server
  namespace: openshift-operators
  finalizers:
    - helm.sdk.operatorframework.io/uninstall-release
spec:
  args:
    manage_routes: false
    agent: as3
    custom-resource-mode: true
    log_level: info
    route-vserver-addr: 172.31.8.220
    openshift-sdn-name: /occ01/occ01-tunnel
    bigip_partition: occ01
    ipam: true
    default-route-domain: 14
    disable-teems: true
    bigip_url: 172.31.8.4
    log_as3_response: true
    insecure: true
    pool-member-type: cluster
  bigip_login_secret: bigip
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
  version: latest
```

In NodePort mode, the integration seems to work.

Documentation does not specify that Flannel is a requirement.

Could you advise us, what is the problem?

Thanks,

Michal Bukovjan
