### ISSUE TITLE
Virtual Server Default Pool not set by CIS in custom resource mode

### ISSUE THREAD

**Issue by azzauzuaz** [F5Networks/k8s-bigip-ctlr#2377]
#### Setup Details
CIS Version : 2.7
Build: f5networks/k8s-bigip-ctlr:2.7.1
BIGIP Version: Big IP 15.1.4 Build 0.0.47 Final
AS3 Version: 3.34.0 Build 4

Agent Mode: AS3
Orchestration: OpenShift Container Platform
Orchestration Version: 4.8.24
Pool Mode: Nodeport

#### Description  
 VirtualServer default pool is not set by CIS deployed in CRD mode

#### Steps To Reproduce
1) Deploy CIS in CRD mode (--custom-resource-mode=true)
2) Deploy Virtual Server

#### Expected Result 
I expect "Default Pool" to be selected correctly.

#### Actual Result  
"Default" Pool is set to "None", hence the Virtual Server Availability: Unknown (Enabled) - The children pool member(s) either don't have service checking enabled, or service check results are not available yet

#### Diagnostic Information
CIS deployment options:
```
--credentials-directory
/tmp/creds
--agent=as3
--as3-validation=true
--bigip-partition=CIS
--bigip-url=https://ltm-azure-cis-test.snam.it
--insecure=true
--log-as3-response=true
--log-level=debug
--manage-configmaps=false
--manage-ingress=false
--manage-routes=false
--pool-member-type=nodeport
--share-nodes=true
--custom-resource-mode=true
```  
VIP deployment template:
```
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: test-nginx
  namespace: f5-test-nginx
spec:
  pools:
  - monitor:
      interval: 5
      send: "GET /\r\n"
      timeout: 16
      type: http
    path: /
    service: nginx-http
    servicePort: 80
  virtualServerAddress: 10.126.19.73
  virtualServerName: test-nginx-vs
```

**Comment by czoczo** [comment]
+1 on the issue above. I do too observe such behavior. I have very similar configuration.

My VS:
```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.138.0.33"
  persistenceProfile: source-address
  pools:
  - path: /
    service: nginx-nodeport
    servicePort: 80
    monitor:
      type: http
      send: "GET /rn"
      recv: ""
      interval: 10
      timeout: 10
```

**My setup Details:**
CIS Version : 2.8
Build: f5networks/k8s-bigip-ctlr:2.8.1
BIGIP Version: Big IP 15.1.2.1 Build 0.0.10 Point Release 1
AS3 Version: 3.32.0 Build 4

Agent Mode: AS3
Orchestration: Kubernetes v1.20.12
Pool Mode: Nodeport

[This](https://github.com/F5Networks/k8s-bigip-ctlr/issues/2317) issue might have something in common. In my case configuring TransportServer populates "Default Pool"
