### ISSUE TITLE
[Question] How can I setup my clientSSL to my Service with type LoadBalancer

### ISSUE THREAD

**Issue by brunocascio** [F5Networks/k8s-bigip-ctlr#2386]
Hey folks,

Just a question, I'm trying to implement CIS with IPAM, without the f5 ingress crd.

Can I add my clientSSL profile to my service? Something like

```yaml
apiVersion: V1
kind: Service
annotations:
   cis.f5.com/ipamLabel: dev
   virtual-server.f5.com/clientssl: '[{ "bigIpProfile": "myprofile" }]'    <---    # is this possible?
spec:
   type: LoadBalancer
   selector:
       app: myapp
   ports:
      - target: 80
         port: 80
```

Thanks
