### ISSUE TITLE
Ability to set logging profile to use on a virtual service via an ingress definition

### ISSUE THREAD

**Issue by sorrison** [F5Networks/k8s-bigip-ctlr#2506]
#### Title
Ability to set logging profile to use on a virtual service via an ingress definition

#### Description
Want to set logging profile on a virtual server using an ingress definition.

#### Actual Problem
The virtual server that is created for an ingress doesn't have a logging profile set, we won't to get this set to an existing profile.

#### Solution Proposed
Change code somewhere to make this happen :-)

**Comment by trinaths** [comment]
Suggest use CRDs

**Comment by sorrison** [comment]
Hi @trinaths using a CRD I don't think is possible nor desirable. 

Use case:  I have a helm chart (not developed by me) that deploys everything including an ingress which is pretty standard. 

I now want to configure the logging profile on the generated VS that the ingress resource created. 

Is this possible?

I thought with a CRD then I wouldn't be able to use the ingress resource and that would be a pain as I want to have as little code as possible

**Comment by trinaths** [comment]
@sorrison Can you try VS CRD with Policy CRD ? See https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/config_examples/customResource/Policy/sample-policy.yaml

**Comment by sorrison** [comment]
Hi @trinaths I'm not really sure what I'm doing but I have created a policy using

```
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: nectar-logging
  namespace: rctest
spec:
  profiles:
    logProfiles:
      - /Common/nectar-rsyslog
```

But I don't see any of the virtual servers created by the ingress resources change to use that logging profile. Is there something else I need to do?
