### ISSUE TITLE
Monitor name by accident includes health check command

### ISSUE THREAD

**Issue by jokoyuliantoro** [F5Networks/k8s-bigip-ctlr#2507]
#### Setup Details
 CIS Version : 2.9      
 Build: f5networks/k8s-bigip-ctlr:2.9.1       
 BIGIP Version: Big IP      
 AS3 Version: 3.38.0
 Agent Mode: AS3
 Orchestration: K8S
 Orchestration Version: 1.24.3
 Pool Mode: Nodeport      
 Additional Setup details: Platform UDF/CNI Cilium

#### Description  

Monitor name includes health check command (with space) that violates the object name pattern (without space).

#### Steps To Reproduce
Create a VS CRD in nginx-ingress namespace to trigger AS3 declaration sending from CIS to BIG-IP.
```
ubuntu@k8s-master:~$ cat echo-api-vs.yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-echo-api
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: echo.example.com
  hostGroup: "echo"
  ipamLabel: Test
  virtualServerHTTPPort: 80
  snat: auto
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: "GET /api HTTP/1.1\r\nHost: echo.example.com\r\n"
      timeout: 10
      type: http
    path: /api
    service: nginx-ingress
    servicePort: 80
ubuntu@k8s-master:~$

```
#### Expected Result 

AS3 declaration is applied in BIG-IP.

#### Actual Result  

No configuration change in BIG-IP.

#### Diagnostic Information
CIS Debug Error Message:
```
2022/07/22 17:51:21 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/k8s/Shared: propertyName "nginx_ingress_nginx_ingress_http_80GET _api HTTP_1_1\r\nHost_ echo_example_com\r\n" should match pattern "^[A-Za-z]([0-9A-Za-z_.-]{0,188}[0-9A-Za-z_.])?$"] message:declaration is invalid] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.18.0/as3-schema-3.18.0-4.json","class":"AS3","declaration":{"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.9.1 K8S/v1.24.3"},"id":"urn:uuid:B97DFADF-9F0D-4F6C-8D66-E9B52E593694","k8s":{"Shared":{"class":"Application","crd_10_1_10_200_80":{"source":"0.0.0.0/0","translateServerAddress":true,"translateServerPort":true,"class":"Service_HTTP","virtualAddresses":["10.1.10.200"],"virtualPort":80,"snat":"auto","policyEndpoint":"/k8s/Shared/crd_10_1_10_200_80_echo_policy"},"crd_10_1_10_200_80_echo_policy":{"class":"Endpoint_Policy","rules":[{"name":"vs_echo_api_nginx_ingress_80_nginx_ingress_echo_example_com","conditions":[{"type":"httpHeader","name":"host","event":"request","all":{"values":["echo.example.com"],"operand":"equals"}},{"type":"httpUri","name":"1","event":"request","index":1,"pathSegment":{"values":["api"],"operand":"equals"}}],"actions":[{"type":"forward","event":"request","select":{"pool":{"use":"nginx_ingress_80_nginx_ingress_echo_example_com"}}}]}],"strategy":"first-match"},"nginx_ingress_80_nginx_ingress_echo_example_com":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["10.1.1.5"],"servicePort":30948},{"addressDiscovery":"static","serverAddresses":["10.1.1.6"],"servicePort":30948}],"monitors":[{"use":"/k8s/Shared/nginx_ingress_nginx_ingress_http_80GET _api HTTP_1_1\r\nHost_ echo_example_com\r\n"}]},"nginx_ingress_nginx_ingress_http_80GET _api HTTP_1_1\r\nHost_ echo_example_com\r\n":{"class":"Monitor","interval":20,"monitorType":"http","targetAddress":"","timeout":10,"timeUntilUp":0,"adaptive":false,"dscp":0,"receive":"none","send":"GET /api HTTP/1.1\r\nHost: echo.example.com\r\n","targetPort":0},"template":"shared"},"class":"Tenant","defaultRouteDomain":0},"label":"CIS Declaration","remark":"Auto-generated by CIS","schemaVersion":"3.18.0"}}
2022/07/22 17:51:21 [ERROR] [AS3] Big-IP Responded with code: 422
```
#### Observations (if any)
N/A
