### ISSUE TITLE
CIS+Openshift 4.10 dual stack

### ISSUE THREAD

**Issue by stwhite5** [F5Networks/k8s-bigip-ctlr#2555]
#### Setup Details
 CIS Version : 2.9.1    
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.3
 AS3 Version: 3.18      
 Agent Mode: AS3      
 Orchestration: OSCP      
 Orchestration Version:       
 Pool Mode: Cluster  
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>
```
oc get networks cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Network
spec:
  clusterNetwork:
  - cidr: 192.168.0.0/16
    hostPrefix: 23
  - cidr: fdxx::/48
    hostPrefix: 64
  externalIP:
    policy: {}
  networkType: OVNKubernetes
  serviceNetwork:
  - 198.x.0.0/16
  - fdxx:xxxx:xxxx::/112
status:
  clusterNetwork:
  - cidr: 192.168.0.0/16
    hostPrefix: 23
  - cidr: fdxx::/48
    hostPrefix: 64
  clusterNetworkMTU: 8500
  networkType: OVNKubernetes
  serviceNetwork:
  - 198.x.0.0/16
  - fdxx:xxxx:xxxx::/112
```

CIS config:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: k8s-bigip-0-ctlr-deployment
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-bigip-0-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-bigip-0-ctlr
      name: k8s-bigip-0-ctlr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeType
                operator: NotIn
                values:
                - loadbalancer
      containers:
      - args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=[BIGIP_ADDRESS]
        - --bigip-partition=kubernetes
        - --insecure=true
        - --agent=as3
        - --namespace=f5
        - --pool-member-type=cluster
        - --as3-validation=true
        - --manage-ingress=false
        - --manage-routes=false
        - --custom-resource-mode=false
        - --manage-configmaps=true
        - --log-level=DEBUG
        - --log-as3-response=true
        - --openshift-sdn-name=/Common/ingress
        command:
        - /app/bin/k8s-bigip-ctlr
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
        image: private_repository/f5/cis/k8s-bigip-ctlr:2.9.1
        imagePullPolicy: IfNotPresent
        name: k8s-bigip-ctlr
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: k8s-bigip-ctlr
      serviceAccountName: k8s-bigip-ctlr
      terminationGracePeriodSeconds: 30
```

#### Description  

CIS installed in OSCP 4.10 dual stack configuration. k8s-bigip-ctlr cannot create tunnels due to V6 addresses. From the CIS logs:

```
2022/08/22 14:54:47 [ERROR] [VxLAN] Bad IPv4 address format specified for FDB record: <node ipv6 address>
2022/08/22 14:54:47 [ERROR] [VxLAN] Bad IPv4 address format specified for FDB record: <node ipv6 address>
2022/08/22 14:54:47 [ERROR] [VxLAN] Bad IPv4 address format specified for FDB record: <node ipv6 address>
2022/08/22 14:54:47 [ERROR] [VxLAN] Bad IPv4 address format specified for FDB record: <node ipv6 address>
2022/08/22 14:54:47 [ERROR] [VxLAN] Bad IPv4 address format specified for FDB record:<node ipv6 address>
2022/08/22 14:54:47 [DEBUG] [CCCL] ConfigWriter (0xc000415aa0) writing section name vxlan-fdb
2022/08/22 14:54:47 [DEBUG] [CCCL] ConfigWriter (0xc000415aa0) successfully wrote section (vxlan-fdb)
2022/08/22 14:54:47 [DEBUG] [VxLAN] Vxlan manager (ocp-ingress) wrote config section: [{ <node ipv6 address>} { <node ipv6 address>} { <node ipv6 address>} { <node ipv6 address>} { <node ipv6 address>}]
```

#### Steps To Reproduce

1) Install and configure OSCP4.10
2) Install and configure CIS 2.9.1
3) get logs of k8s-bigip-ctlr pod

#### Expected Result 

vxlan tunnels will be created using IPv4 addresses

#### Actual Result  

vxlan tunnel creation fails because CIS submits IPv6 addresses via IPv4 config, failing with bad address format.

#### Observations (if any)

The current configuration works properly with OSCP 4.7. I have not tested with OSCP 4.10 single-stack V4 because my customer requires dual stack functionality in OSCP/CIS
