### ISSUE TITLE
[CONTCNTR-3584] Unable to configure SNI with openshift routes

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#2571]
#### Setup Details
 CIS Version : 2.9.0
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1      
 AS3 Version: 3.34      
 Agent Mode: AS3       
 Orchestration: OSCP      
 Orchestration Version: 4.8      
 
#### Description  
I am opening this ticket on behalf of a customer. 
They have configured the "default-client-ssl" certificate (which is set as SNI) on the CIS parameters and they are configuring a route with its own certificate. 
They expect that CIS configures BIGIP to present the route certificate instead of the "default".
CIS is not configuring the route certificate. 

```
##### Route example ######
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  host: www.example.com
  to:
    kind: Service
    name: frontend
  tls:
    termination: edge
    key: |-
      -----BEGIN PRIVATE KEY-----
      [...]
      -----END PRIVATE KEY-----
    certificate: |-
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
```

#### Steps To Reproduce
1) Define a "default-client-ssl" certificate
2) Create a route with it own certificate
3) Access the service and check the certs. it will be the "default" instead of the route/

#### Expected Result 
It is expected CIS to create another SSL profile that will be enabled for that specific route
