### ISSUE TITLE
ADDRESS for Ingress resources is not populated with ip of VirtualServer 

### ISSUE THREAD

**Issue by efaverman** [F5Networks/k8s-bigip-ctlr#2586]
#### Setup Details
 CIS Version : 2.9.1, BuildInfo: azure-2810-a8cd93c79f260b6d48f8ed5149df0ad1f785e3d9      
 Build: f5networks/k8s-bigip-ctlr:2.9.1     
 BIGIP Version: Big IP 16.1.2.1 Build 0.0.10 Point Release 1   
 AS3 Version: 3.36.0-6     
 Agent Mode: AS3       
 Orchestration: K8S     
 Orchestration Version:  v1.20.15
 Pool Mode: Nodeport      

**NGINX Ingress Controller**

Helm chart repo: https://helm.nginx.com/stable
chart_name    = "nginx-ingress"
chart_version = "0.14.0"
```
  containers:
    - name: nginx-ingress
      image: nginx/nginx-ingress:2.3.0
      args:
        - '-nginx-plus=false'
        - '-nginx-reload-timeout=60000'
        - '-enable-app-protect=false'
        - '-enable-app-protect-dos=false'
        - '-nginx-configmaps=$(POD_NAMESPACE)/nginx-ingress'
        - >-
          -default-server-tls-secret=$(POD_NAMESPACE)/nginx-ingress-default-server-tls
        - '-ingress-class=nginx'
        - '-health-status=true'
        - '-health-status-uri=/nginx-health'
        - '-nginx-debug=true'
        - '-v=1'
        - '-nginx-status=true'
        - '-nginx-status-port=8080'
        - '-nginx-status-allow-cidrs=127.0.0.1'
        - '-report-ingress-status'
        - '-external-service=nginx-ingress'
        - '-enable-leader-election=true'
        - '-leader-election-lock-name=nginx-ingress-leader-election'
        - '-enable-prometheus-metrics=true'
        - '-prometheus-metrics-listen-port=9113'
        - '-prometheus-tls-secret='
        - '-enable-custom-resources=true'
        - '-enable-snippets=true'
        - '-enable-tls-passthrough=false'
        - '-enable-preview-policies=false'
        - '-enable-cert-manager=false'
        - '-enable-oidc=false'
        - '-enable-external-dns=true'
        - '-ready-status=true'
        - '-ready-status-port=8081'
        - '-enable-latency-metrics=true'
```

**NGINX service**

```spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30837
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 31937
  selector:
    app: nginx-ingress
  clusterIP: x.x.x.x
  clusterIPs:
    - x.x.x.x
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Local
```

**f5-bigip-ctlr**

```
  containers:
    - name: f5-bigip-ctlr
      image: f5networks/k8s-bigip-ctlr:2.9.1
      command:
        - /app/bin/k8s-bigip-ctlr
      args:
        - '--credentials-directory'
        - /tmp/creds
        - '--agent=as3'
        - '--bigip-partition=k8s'
        - '--bigip-url=https://mybigip.f5.com/'
        - '--custom-resource-mode=true'
        - '--insecure=true'
        - '--ipam=true'
        - '--log-as3-response=true'
        - '--log-level=DEBUG'
        - '--manage-ingress=true'
        - '--pool-member-type=nodeport'
```

**Virtual Server**

```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx-virtual-server
  namespace: default
  labels:
    f5cr: "true"
spec:
  tlsProfileName: mywildcardtlsprofile
  httpTraffic: redirect
  virtualServerName: nginx-virtual-server
  virtualServerAddress: "x.x.x.x"
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 80
    monitor:
      type: http
      send: GET /nginx-health HTTP/1.1\r\n
      recv:
      interval: 9
      timeout: 10
    name: nginx_pool_80
```

**Ingress**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress-test
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cafe-ingress.mydomain.net
spec:
  ingressClassName: nginx
  rules:
    - host: cafe-ingress.mydomain.net
      http:
        paths:
          - path: /tea
            pathType: ImplementationSpecific
            backend:
              service:
                name: tea-svc
                port:
                  number: 80
          - path: /coffee
            pathType: ImplementationSpecific
            backend:
              service:
                name: coffee-svc
                port:
                  number: 80
```

#### Description  
VirtualServer created with CRD for service NGINX Ingress Controller has correct ip set in `virtualServerAddress` and works, however ADDRESS \ ```status: loadBalancer: ingress:- ip``` on all Ingress resources remains **_empty_** (unlike services of type LoadBalancer which _do_ get ADDRESS / loadBalancer ingress ip).

#### Impact  
DNS records are not created for Ingress resources.

We have external-dns installed in our cluster and DNS records are only created for Ingress resources which:
* have `external-dns.alpha.kubernetes.io/hostname` annotation
* have Ingress ADDRESS \```status: loadBalancer: ingress:- ip x.x.x.x`` populated.

#### Steps To Reproduce
1) Install CIS and NGINX controller 
2) Create VirtualServer 
3) install test service (e.g.  coffee/tea) with Ingress 
4) `kubectl get ingress` / `kubectl get ingress -o yaml`

#### Expected Result 
```
NAME   CLASS   HOSTS    ADDRESS   PORTS   AGE
cafe-nginx-test   nginx      cafe-ingress.mydomain.net   x.x.x.x   80  21h
```

```
status:
  loadBalancer:
    ingress:
      - ip: x.x.x.x
```

#### Actual Result  
```
NAME   CLASS   HOSTS   ADDRESS   PORTS   AGE
cafe-nginx-test   nginx  cafe-ingress.mydomain.net                  80   21h
```
```
status:
    loadBalancer: {}
```
#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```
