### ISSUE TITLE
WAF policy name does not allow hyphen (-)

### ISSUE THREAD

**Issue by andreasjacobi** [F5Networks/k8s-bigip-ctlr#2657]
#### Setup Details
 CIS Version : 2.10.1      
 Build: f5networks/k8s-bigip-ctlr:2.10.1      
 BIGIP Version: Big IP 16.1.3.2    
 AS3 Version: 3.36.1      
 Agent Mode: AS3       
 Orchestration: K8S  
 Orchestration Version:  1.23.9     
 Pool Mode: Cluster  
 Additional Setup details: Cilium

#### Description  
Assigning a WAF policy under a VS CRD that contains a hyphen (-) return an error from the CRD spec
```
The VirtualServer "grafana-virtual-server" is invalid: spec.waf: Invalid value: "/Common/Rapid-Policy": spec.waf in body should match '^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$'
```

Removing the hyphen (-) works

#### Steps To Reproduce
Create VS with WAF policy:

```
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: grafana-virtual-server
  labels:
    f5cr: "true"
spec:
  host: grafana.example.com
  virtualServerAddress: "10.10.10.10"
  virtualServerName: grafana
  tlsProfileName: grafana-edge-tls
  profileMultiplex: "/Common/oneconnect"
  persistenceProfile: "source-address"
  waf: /Common/Rapid-Policy
  pools:
  - path: /
    service: prometheus-grafana
    servicePort: 3000
    loadBalancingMethod: least-connections-member
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 10
  serviceAddress:
  - icmpEcho: "enable"
    arpEnabled: true
    routeAdvertisement: "all"
    spanningEnabled: false
```

#### Expected Result 

Allow waf policy name with hyphen (-)

#### Actual Result  

WAF policy with hyphen (-) returns an error:
```
The VirtualServer "grafana-virtual-server" is invalid: spec.waf: Invalid value: "/Common/Rapid-Policy": spec.waf in body should match '^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$'
```
