### ISSUE TITLE
Remove unwanted TLS iRule deployed on reencrypt when passing XFF

### ISSUE THREAD

**Issue by pedley-f5** [F5Networks/k8s-bigip-ctlr#2764]
#### Title
Remove unwanted TLS iRule deployed on reencrypt when passing XFF

#### Description
TLS iRule is applied to reencrypt virtualserver resources, even though it doesn't appear to be needed. Here's a sample of the CRs. Removing iRule temporarily doesn't appear to break anything.

```
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: nginx-ingress-tls
  namespace: nginx-ingress1
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip             # --> reference profiles created in BIG-IP by User
  hosts:
    - cafe.example.com
---
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: nginx-ingress-policy
  namespace: nginx-ingress1
spec:
  profiles:
    http: /Common/http-xff
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx-ingress-vs1
  namespace: nginx-ingress1
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  partition: nginx-ingress
  tlsProfileName: nginx-ingress-tls
  virtualServerAddress: "10.1.20.28"
  virtualServerName: "nginx-ingress-vs1"
  httpTraffic: redirect
  policyName: nginx-ingress-policy
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 443
    serviceNamespace: nginx-ingress
    monitor:
      type: https
      interval: 10
      timeout: 31
      send: "/"
      recv: ""
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: nginx-ingress-tls
  namespace: nginx-ingress2
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip             # --> reference profiles created in BIG-IP by User
  hosts:
    - cafe.example.com
---
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: nginx-ingress-policy
  namespace: nginx-ingress2
spec:
  profiles:
    http: /Common/http-xff
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx-ingress-vs2
  namespace: nginx-ingress2
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  partition: nginx-ingress
  tlsProfileName: nginx-ingress-tls
  virtualServerAddress: "10.1.20.29"
  virtualServerName: "nginx-ingress-vs2"
  httpTraffic: redirect
  policyName: nginx-ingress-policy
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 443
    serviceNamespace: nginx-ingress
    monitor:
      type: https
      interval: 10
      timeout: 31
      send: "/"
      recv: ""

```

#### Actual Problem
The iRule doesn't seem to be used in the scenario above, even when inserting XFF and reencrypting. Customer's concern is that if something goes wrong, it's too difficult to troubleshoot.

#### Solution Proposed
Add a flag that enables/disables the iRule insertion.

#### Alternatives
N/A

#### Additional context
N/A
