### ISSUE TITLE
TLSProfile crd is broken when the SSL profile is from Shared location

### ISSUE THREAD

**Issue by pmilot** [F5Networks/k8s-bigip-ctlr#2793]
#### Setup Details
 CIS Version : 2.12.0      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.3.2     
 AS3 Version: 3.42.0      
 Agent Mode: AS3      
 Orchestration: K8S   
 Orchestration Version:  1.24.9
 Pool Mode: Nodeport      

#### Description  
When specifying an SSL profile for TLSProfile  that includes a Shared path location it fails

#### Steps To Reproduce
1)Create an SSL Profile in a Shared location example /Common/Shared/k8s_ingress_clientside_tls_profile
2)Create TLSProfile with path to shared location
```
apiVersion: cis.f5.com/v1
 kind: TLSProfile
 metadata:
   namespace: istio-system
   name: statusdemo-tls
   labels:
     f5cr: "true"
 spec:
   tls:
     termination: reencrypt
     clientSSL: "/Common/Shared/k8s_ingress_clientside_tls_profile"
     serverSSL: /Common/serverssl
     reference: bigip            # --> reference profiles created in BIG-IP by User
   hosts:
   - demo.gateway.test.local
 ```
3)The CIS sends the AS3 declaration is a bad path to the SSL profile

"clientTLS":[{"bigip":"/Common/serverssl"}],"serverTLS":[{"bigip":"//"}]

#### Expected Result 
Path to the SSL profile should be correct:

"clientTLS":[{"bigip":"/Common/serverssl"}],"serverTLS":[{"bigip":"/Common/Shared/k8s_ingress_clientside_tls_profile"}]

#### Actual Result  
Path to the SSL profile is mangled with only slashes:
[ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: message:Unable to find // for /pmrke2v1-cluster/Shared/demo_gateway_test_local_tls_443/serverTLS/0]

"clientTLS":[{"bigip":"/Common/serverssl"}],"serverTLS":[{"bigip":"//"}]

#### Diagnostic Information

```  

#### Observations (if any)
