### ISSUE TITLE
AS3 config updated in LTM Nodes every 30 seconds by k8s-bigip-ctlr

### ISSUE THREAD

**Issue by marcoval123** [F5Networks/k8s-bigip-ctlr#2850]
#### Setup Details
 CIS Version : 2.10.1     
 Build: f5networks/k8s-bigip-ctlr:2.10.1    
 BIGIP Version: Big IP 2.10.1  
 AS3 Version: 3.26.1      
 Agent Mode: AS3       
 Orchestration: K8S
 Orchestration Version: 1.23.8       
 Pool Mode: Cluster      
 Additional Setup details: None

#### Description  

We detect high CPU in LTM Nodes because the k8s-bigip-ctlr is uploading AS3 config every 30 seconds. We assume that the controller detects a change in the Kubernetes API and creates a new AS3 config.

We have observed that, when the k8s-bigip-ctlr updates AS3 config to  LTM Nodes, no changes are detected in the Kubernetes API. In the "Obervations" section, we indicate the tests performed to see what causes this problem.

Could you provide us some procedure to see what changes the controller detects that triggers the AS3 change?

#### Steps To Reproduce
Environment with X Ingresses resources, one of them a default backend, with the Ingress Controller exposed by k8s-bigip-ctlr.

1) Creating a new Ingress Resources with the Ingress Controller exposed by k8s-bigip-ctlr.
2) The k8s-bigip-ctrl upload, every 30 seconds, a new AS3 config.

We not found a specific Ingress Resource configuration that causes the problem mentioned above.

#### Expected Result 

The AS3 file is not updated every 30 seconds.

#### Actual Result  
The AS3 file is updated every 30 seconds because a change.

#### Observations (if any)

We have performed the following tests to identify the cause of the problem:

1. With DEBUG feature enabled, we cannot see what changes the controler has detected. Only the following message is reported:
....
2023/03/17 12:56:21 [DEBUG] [CORE] Updated 2 of 16 virtual server configs, deleted 0
....
2023/03/17 12:56:22 [DEBUG] [CORE] Updated 2 of 6 virtual server configs, deleted 0
....
2023/03/17 12:56:22 [DEBUG] [CORE] Updated 2 of 4 virtual server configs, deleted 0
....

2. About changes in Kubernetes API, we see that k8s-bigip-ctlr is doing a http request to "/api/v1/<RESOURCE>?allowWatchBookmarks=true&resourceVersion=249253011&timeoutSeconds=387&watch=true" awaiting changes
  where <RESOURCE> is: 
   - apis/networking.k8s.io/v1/ingressclasses
   - apis/networking.k8s.io/v1/ingresses
   - /api/v1/configmaps
   - /api/v1/endpoints
   - /api/v1/namespaces
   - /api/v1/secrets
   - /api/v1/services

      We have done the same request, and no changes are detected when k8s-bigip-ctlr upload a AS3 config to LTM Nodes.

3. On "/var/log/restjavad-audit.0.log" file, located on LTM Nodes, we see http requests that change AS3 configuration.

**Comment by trinaths** [comment]
@marcoval123 - We fixed these issues in latest versions. Recommend upgrade CIS to 2.12.1 and share your feedback.

**Comment by marcoval123** [comment]
Hi @trinaths,

Today, we have upgraded CIS to 2.12 and we see the same problems mentioned above.

We have a default backend pointing to the ingress class exposed by k8s-bigip-ctlr, and when is created, the AS3 config is updated every 30 seconds with the following message:

```bash
[DEBUG] [AS3] Posting AS3 Declaration
[DEBUG] [AS3] posting request to https://xxxx/mgmt/shared/appsvcs/declare/
```

Here is the ingress yaml used to define a default backend:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "false"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: ZZZZZ
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    virtual-server.f5.com/clientssl: '[ { "bigIpProfile": "/Common/YYYYYY"} ]'
  name: upc-bigip-ctlr-default-backend
  namespace:XXXX
spec:
  defaultBackend:
    service:
      name: upc-bigip-ctlr-default-backend
      port:
        number: 80

```
When we delete the default backend, no changes are detected on kubernetes cluster.

Apart from that, we have a few ingress resources created that are exposed by ltm nodes without problems.

Could you provide us some procedure to see what changes the controller detects that triggers the AS3 change?
