### ISSUE TITLE
How to implement different virtual servers, using the same domain name, doing edns resolution through crd mode?

### ISSUE THREAD

**Issue by lefeck** [F5Networks/k8s-bigip-ctlr#2894]
#### Setup Details
CIS Version : 2.12.1
BIGIP Version: Big IP 16.1.3
AS3 Version: 3.44
Agent Mode: CRD
Orchestration: K8S
Pool Mode: Cluster

```yaml
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=https://192.168.10.88", 
            "--insecure=true",
            "--bigip-partition=kubernetes",
            "--pool-member-type=cluster",
            "--custom-resource-mode=true"
          ]
```

#### Description  

I'm trying to do edns resolution through multiple different Virtual Server addresses, using the same domain name, and I'm finding that in [DNS] -> [GSLB : Pools : Pool List]-> Members . There is always only one virtual server address.

#### Steps To Reproduce
1) Created crd configuration in k8s
2) Created Deployment, Service, VirtualServer resource object configurations

#### Expected Result

in bigip, [DNS] ››  [GSLB : Pools : Pool List] ››  Members : mysite.f5test.com_192_168_10_88_kubernetes_gtm : A, there should be 2 virtual server addresses: 172.16.3.4 and 172.16.3.5

#### Actual Result  

When I configure the virtual server, and then configure the externaldns instance, I find that there is only one ip address 172.16.3.4 in GSLB -> member. 

Below is a screenshot of the bigip device:

![edns1](https://github.com/lefeck/linuxbasic/blob/main/img/edns1.png)

![edns](https://github.com/lefeck/linuxbasic/blob/main/img/edns.png)

![edns2](https://github.com/lefeck/linuxbasic/blob/main/img/edns2.png)

#### Diagnostic Information

Here is an example of my configuration.
```yml
[root@master test]# cat deploy-tea.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tea 
  template:
    metadata:
      labels:
        app: tea 
    spec:
      containers:
      - name: tea 
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-tea
  labels:
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tea
  type: ClusterIP
[root@master test]# cat edns-mysite-test.yaml
apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-mysite-test
  labels:
    f5cr: "true"
spec:
  domainName: mysite.f5test.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/bigip
    monitor:
      type: http
      send: "GET / HTTP/1.1\r\nHost: mysite.f5test.com\r\n"
      recv: ""
      interval: 10
      timeout: 30
[root@master test]# cat vs-test.yaml
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: test-virtual
  namespace: default
spec:
  host:  mysite.f5test.com
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: http-tea
    servicePort: 80
  virtualServerAddress: 172.16.3.4
  additionalVirtualServerAddresses:
  - "172.16.3.5"
[root@master test]# 
[root@master test]# kubectl get svc
NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
app-server-canary-svc   ClusterIP   10.96.57.166    <none>        8080/TCP            8d
app-server-stable-svc   ClusterIP   10.96.137.249   <none>        8080/TCP            8d
details                 ClusterIP   10.96.241.56    <none>        9080/TCP            58m
http-coffee             ClusterIP   10.96.129.45    <none>        80/TCP              12d
http-tea                ClusterIP   10.96.101.2     <none>        80/TCP              12d
[root@master test]# kubectl get vs
NAME                  HOST                TLSPROFILENAME   HTTPTRAFFIC   IPADDRESS        IPAMLABEL   IPAMVSADDRESS    STATUS   AGE
test-virtual          mysite.f5test.com                                  172.16.3.4                   172.16.3.4       Ok       2d22h
[root@master test]# kubectl get edns
NAME               DOMAINNAME          AGE     CREATED ON
edns-mysite-test   mysite.f5test.com   27m     2023-05-22T02:35:12Z
[root@master test]# 
```
