### ISSUE TITLE
"should have required property 'servicePort'" error creating a TransportServer

### ISSUE THREAD

**Issue by brunocascio** [F5Networks/k8s-bigip-ctlr#2914]
#### Setup Details
 CIS Version : 2.13.0
 Build: f5networks/k8s-bigip-ctlr:2.13.0       
 BIGIP Version: Big IP 15.1.6 
 AS3 Version: 3.33    
 Agent Mode: AS3       
 Orchestration: K8S
 Orchestration Version:  1.20.12
 Pool Mode: Nodeport      
 Additional Setup details: Antrea / Containerd

#### Description  
 
Creating a TransportServer for rabbitmq throws a silent (debug) error

```
2023/06/05 17:36:33 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: errors:[/dev-nonprod-k8s-cis/Shared/rabbitmq_cluster_5672_rabbitmq/members/0: should have required property 'servicePort'] message:declaration is invalid] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.33.0/as3-schema-3.33.0-4.json","class":"AS3","declaration":{"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.13.0 K8S/v1.20.12+vmware.1"},"dev-nonprod-k8s-cis":{"Shared":{"class":"Application","crd_10_x_x_x_5672":{"class":"Service_TCP","virtualAddresses":["10.x.x.x"],"virtualPort":5672,"snat":"auto","pool":"rabbitmq_cluster_5672_rabbitmq","profileL4":"basic"},"rabbitmq_cluster_5672_rabbitmq":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["172.17.68.51"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.53"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.52"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.62"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.59"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.34"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.39"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.32"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.38"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.57"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.54"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.40"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.41"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.18"],"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.49"],"shareNodes":true}],"monitors":[{"use":"/dev-nonprod-k8s-cis/Shared/rabbitmq_cluster_rabbitmq_tcp_5672"}]},"rabbitmq_cluster_rabbitmq_tcp_5672":{"class":"Monitor","interval":10,"monitorType":"tcp","targetAddress":"","timeout":10,"adaptive":false,"receive":"","send":""},"template":"shared"},"class":"Tenant","defaultRouteDomain":0},"id":"urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d","label":"CIS Declaration","remark":"Auto-generated by CIS","schemaVersion":"3.33.0"}}
```

#### Steps To Reproduce

```yaml
apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  name: rabbitmq-ts
  namespace: f5-nonprod
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.x.y.z"
  virtualServerPort: 5672 
  type: tcp
  mode: standard
  snat: auto
  pool:
    service: rabbitmq-cluster
    servicePort: 5672
    monitor:
      type: tcp
      interval: 10
      timeout: 10
```
2) Open f5 CIS logs

#### Expected Result 
- controller should configure bigip with the transport server configuration

#### Actual Result  
- Error about schema properties

#### Observations (if any)

- I'm using the same VIP also for an ingress resource, don't know if it could generate problems but would be great to use the same VIP

**Comment by mdditt2000** [comment]
@brunocascio message:declaration is invalid. Was this working before 2.13? Or never worked?

**Comment by mdditt2000** [comment]
AS3 Json
https://github.com/mdditt2000/openshift-4-11/blob/main/GitHub/2914/as3.json

AS3 response
https://github.com/mdditt2000/openshift-4-11/blob/main/GitHub/2914/response.json

Humm why doesnt BIG-IP like the declaration. Posted outside of CIS using REST and get the same issue. Standby as i look at the format of the declaration

**Comment by brunocascio** [comment]
> @brunocascio message:declaration is invalid. Was this working before 2.13? Or never worked?

This is my first try with TransportServer, so don't know if it works or not with previous versions unfortunately

**Comment by brunocascio** [comment]
> AS3 Json https://github.com/mdditt2000/openshift-4-11/blob/main/GitHub/2914/as3.json
> 
> AS3 response https://github.com/mdditt2000/openshift-4-11/blob/main/GitHub/2914/response.json
> 
> Humm why is the "servicePort": missing?

Could it be related to the `shared-node: true` flag somehow?

**Comment by mdditt2000** [comment]
This works

https://github.com/mdditt2000/openshift-4-11/blob/main/GitHub/2914/as3-working.json

CIS is not adding the service port. Weird. I need to look into that. 

Maybe its Shared Node. Are you going to share Node IP on the BIG-IP?

**Comment by brunocascio** [comment]
> @brunocascio please can you share the service definition. Please send mail to [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com)

When I was copying the service I figured out I didn't set the NodePort type 😆 but now I configured it with NodePort and I get a different error: 

```
2023/06/06 16:21:45 [ERROR] [AS3] Raw response from Big-IP: map[code:422 kind::resterrorresponse message:request failed with null exception referer:172.17.68.63 restOperationId:8.40709713e+08] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.33.0/as3-schema-3.33.0-4.json","class":"AS3","declaration":{"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.13.0 K8S/v1.20.12+vmware.1"},"dev-nonprod-k8s-cis":{"Shared":{"class":"Application","crd_10_12_204_254_5672":{"class":"Service_TCP","virtualAddresses":["10.12.204.254"],"virtualPort":5672,"snat":"auto","pool":"rabbitmq_cluster_nodeport_5672_rabbitmq","profileL4":"basic"},"rabbitmq_cluster_nodeport_5672_rabbitmq":{"class":"Pool","members":[{"addressDiscovery":"static","serverAddresses":["172.17.68.51"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.53"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.52"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.62"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.59"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.34"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.39"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.32"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.38"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.57"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.54"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.40"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.41"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.18"],"servicePort":32680,"shareNodes":true},{"addressDiscovery":"static","serverAddresses":["172.17.68.49"],"servicePort":32680,"shareNodes":true}],"monitors":[{"use":"/dev-nonprod-k8s-cis/Shared/rabbitmq_cluster_nodeport_rabbitmq_tcp_5672"}]},"rabbitmq_cluster_nodeport_rabbitmq_tcp_5672":{"class":"Monitor","interval":10,"monitorType":"tcp","targetAddress":"","timeout":10,"adaptive":false,"receive":"","send":""},"template":"shared"},"class":"Tenant","defaultRouteDomain":0},"id":"urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d","label":"CIS Declaration","remark":"Auto-generated by CIS","schemaVersion":"3.33.0"}}
```

Sure!

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-nodeport
spec:
  type: NodePort
  ports:
    - appProtocol: amqp
      name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
```

**Comment by mdditt2000** [comment]
@brunocascio 
I see the As3 declaration composed by CIS is valid
Could able to successfully post the declaration to the BIGIP without any issues. I got success as well. 

--

After setting the properly to NodePort, serviceport issue was resolved based on your latest comment. 

```
          "members": [
                        {
                            "addressDiscovery": "static",
                            "serverAddresses": [
                                "172.17.68.51"
                            ],
                            "servicePort": 32680,
                            "shareNodes": true
                        },
```

[9:34 AM] Nanda Kishore PEDDI

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-05T09:36:23Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "25090619"
  uid: 9350d51a-9659-4b06-a37c-8f54f17fb71e
spec:
  clusterIP: 172.30.110.129
  clusterIPs:
  - 172.30.110.129
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31588
    port: 32111
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort

Definition of Server where the port is 32111 and nodePort is 31588 and we ignore targetPort:80 in CIS Nodeport Mode

```
We can insist user to try using 

servicePort: 5672

 aligned with 

port: 32111

instead of targetPort of service
```

**Comment by mdditt2000** [comment]
@brunocascio can i close this issue?

**Comment by mdditt2000** [comment]
Note

The last error reported is 

```
[code:422 kind::resterrorresponse message:request failed with null exception referer:172.17.68.63 restOperationId:8.40709713e+08]
```
This might go away with possible retry post AS3 calls by CIS.

**Comment by mdditt2000** [comment]
@brunocascio K8S dont believe version will make a different. Can you share you application with my team so we can recreate internal. Please email me at automation_toolchain_pm@f5.com or share here

**Comment by brunocascio** [comment]
> @brunocascio K8S dont believe version will make a different. Can you share you application with my team so we can recreate internal. Please email me at [automation_toolchain_pm@f5.com](mailto:automation_toolchain_pm@f5.com) or share here

Created same example with a dummy app, getting the same error:

```
2023/06/08 17:45:42 [ERROR] [AS3] Raw response from Big-IP: map[code:422 kind::resterrorresponse message:request failed with null exception referer:172.17.68.63 restOperationId:8.48080957e+08] {"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.33.0/as3-schema-3.33.0-4.json","class":"AS3","declaration":{"class":"ADC","controls":{"class":"Controls","userAgent":"CIS/v2.13.0 K8S/v1.20.12+vmware.1"},"dev-nonprod-k8s-cis":{"Shared":{"class":"Application","crd_10_12_204_254_32222":{"class":"Service_TCP","virtualAddresses":["10.12.204.254"],"virtualPort":32222,"snat":"auto","pool":"test_32222_app_devops_techweek_dev","profileL4":"basic"},"template":"shared","test_32222_app_devops_techweek_dev":{"class":"Pool"}},"class":"Tenant","defaultRouteDomain":0},"id":"urn:uuid:85626792-9ee7-46bb-8fc8-4ba708cfdc1d","label":"CIS Declaration","remark":"Auto-generated by CIS","schemaVersion":"3.33.0"}}
```


```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app:  test
    spec:
      containers:
      - name:  test
        image:  nexus.itspty.com:5002/nginx:stable-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name: nginx-http
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: tcp-80
    appProtocol: TCP
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32222
---
apiVersion: cis.f5.com/v1
kind: TransportServer
metadata:
  name: test
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.12.204.254"
  virtualServerPort: 32222 
  type: tcp
  mode: standard
  snat: auto
  pool:
    service: test
    servicePort: 32222
```
