### ISSUE TITLE
multicluster preview: mode setting should be per cluster and orthogonal to CIS HA

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#2989]
#### Title
multicluster preview: mode setting should be per cluster and orthogonal to CIS HA

#### Description

Note: this is not a customer request 

In the multicluster preview, workload settings are set in the HighAvailability section for the primary and secondary CIS. 

I find that the workload settings should be able to be applied for each cluster independently regardless these are primaryCIS/secondayCIS or externally managed. From workload point of view they are equal unless using active-standby mode:

#### Solution Proposed

```
extendedSpec: |
  multiclusterCIS:
    primaryClusterEndPoint: 
      - bigip1: http://10.145.72.114:8001
      - bigip2: http://10.145.72.114:8002
    probeInterval: 30
    retryInterval: 3
    primaryCluster:
      clusterName: cluster1
    secondaryCluster:
      clusterName: cluster2
  multiClusterWorkloads:
  - clusterName: cluster1
    secret: default/kubeconfig1
    adminStatus: disable
    ratio: 1
  - clusterName: cluster3
    secret: default/kubeconfig3
    ratio: 2 
    adminStatus: disable
  - clusterName: cluster3
    secret: default/kubeconfig3
    ratio: 2
    adminStatus: enable 
```
The purpose of this is to have a symmetric configuration that can be automated more easily (the parameters don´t change their location)
