### ISSUE TITLE
multicluster preview: ability to disable and force-offline a whole cluster

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3072]
#### Title
multicluster preview: ability to disable and force-offline a whole cluster

#### Description

Customer wants to drain the connections to a cluster in a gracefully manner, for this it is required to implement in a per-cluster level. the following knobs currently available at pool level (not exposed in CIS):

- disable: Disallows the allocation of new, unpersisted connections. When disabled, the node or pool member continues to process persistent and active connections. It can accept new connections only if the connections belong to an existing persistence session. Those persistence matches for new connections continue until persistence times out.

- force-offline: Specifies that a node or pool member allows existing connections to time out, but no new connections are allowed.

This requires sending connections to the other(s) clusters when the connection is not admitted in a cluster.

#### Actual Problem

This is required to drain the connections of a cluster gracefully.

#### Solution Proposed

Add an adminStatus parameter to the extendedSpec of the globalConfigMap:

```
    extendedSpec: |
      mode: ratio
      highAvailabilityCIS:
        primaryEndPoint: http://10.1.10.5:30000/health
        probeInterval: 30
        retryInterval: 3
        primaryCluster:
          clusterName: ocp1
          secret: kube-system/kubeconfig.ocp1
          ratio: 80
          adminStatus: [ enable, disable, force-offline]
        secondaryCluster:
          clusterName: ocp2
          secret: kube-system/kubeconfig.ocp2
          ratio: 2
          adminStatus: [ enable, disable, force-offline]          
```
