### ISSUE TITLE
RFE: NextGen Routes ConfigMap and MultiCluster requires separate namespaces for each CIS

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3100]
#### Title

NextGen Routes requires separate namespaces for each CIS

#### Description
I wanted to highlight a behaviour I find should be improved:

- at present it is required to have a separate configmap for each bigip because it is required a different health end-point monitor for each CIS

- given that it is required to specify the configmap´s namespace as --namespace parameter in order this to monitored if modified it means that each CIS instance requires different namespace for itself, this further complicates things

#### Actual Problem

Requiring two configmaps is already an unnecessary complication IMHO, this additionally triggers the need of CIS namespace sepration, making things one more bit more complicated.

#### Solution Proposed

Please consider having a more simple configuration which requires less namespaces and modifications between the different instances of CIS

**Comment by alonsocamaro** [comment]
Then it is required a third namespace for common things like policies, ie:
```
      extendedRouteSpec:
      - namespace: xyz
        vserverAddr: 10.1.10.102
        vserverName: xyz
        bigIpPartition: xyz
        allowOverride: true
        policyCR: cis-common/policy-default
```
