### ISSUE TITLE
Multi-cluster CIS generates errors and downed pools

### ISSUE THREAD

**Issue by pmilot** [F5Networks/k8s-bigip-ctlr#3284]
#### Title
CIS running in a remote cluster causes errors and downed pools when the app is not deployed locally

#### Description
We have a use case to run the CIS in a cluster where the applications may not exist in the local cluster.  When controller mode is set to mode: ratio, CIS cannot discover the app in the local cluster generating an error in the logs (not a big deal) but also creates a pool with no members marked down (RED).

#### yaml files 
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: global-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    mode: ratio
    externalClustersConfig:
    - clusterName: pmrke2
      secret: kube-system/kubeconfig-pmrke2
      ratio: 90
    - clusterName: pmrke3
      secret: kube-system/kubeconfig-pmrke3
      ratio: 10
```

```
spec:
  virtualServerAddress: 10.1.201.176
  host: cafe.example.com
  pools:
    - path: /coffee
      service: coffee-svc
      servicePort: 8080
      extendedServiceReferences:
        - clusterName: pmrke2
          namespace: cafe
          port: 8080
          serviceName: coffee-svc
        - clusterName: pmrke3
          namespace: cafe
          port: 8080
          serviceName: coffee-svc
```

```
# show ltm pool coffee_svc_8080_cafe_cafe_example_com
Ltm::Pool: coffee_svc_8080_cafe_cafe_example_com
---------------------------------------------------------------------------------------
Status
  Availability           : offline
  State                  : enabled
  Reason                 :
  Monitor                : none
  Minimum Active Members : 1
  Priority Groups        : 0/0/0 (highest/current/lowest)
  Current Active Members : 0
  Available Members      : 0
  Total Members          : 0
  Total Requests         : 0
  Current Sessions       : 0
```

#### Solution Proposed
Currently we can be deliberate about telling CIS where the APP is deployed in the extendedServiceReferences: by calling out the remote clusters.  It would be nice if we had a way to define to CIS if the App is expected to be deployed in the local cluster to clean up the logs and pools.

Perhaps by making the servie: and port: optional in the CRD when extendedServiceReference: is present in the CRD 

#### Alternatives
I also tried adding this primaryCluster config and setting the adminState to stand alone but as expected CIS still tries to discover the apps in the local cluster

```
    highAvailabilityCIS:
      primaryCluster:
        clusterName: pmrke1
        secret: kube-system/kubeconfig-pmrke1
        adminState: offline
```
#### Use cases
We have two use case where this can be useful

1) Running CIS in a "longlived" cluster where other CICD components are running.  This would allow to rotate application clusters for upgrade purposes without having to move the CIS controller around and changing roles from Primary/Secondary on a regular basis

2) Allow for promoting applications from one cluster to another in phased approach, where not all applications may live in the CIS local cluster at any given time.

Functionally this seems to work if I ignore the downed pools and log errors.
