### ISSUE TITLE
Override AS3 ConfigMap

### ISSUE THREAD

**Issue by aswoad-tech** [F5Networks/k8s-bigip-ctlr#3293]
Setup Details
 CIS Version : 2.15.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1.8      
 AS3 Version: 3.48.0
 Agent Mode: AS3/CCCL       
 Orchestration: OSCP      
 Orchestration Version: OpenShift 4.14.6       
 Pool Mode: Cluster
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

Description
I would like to take advantage of CIS integration with OpenShift using OVN-Kubernetes CNI with NO tunnels plus SNAT pool for each Virtual Server.

Steps To Reproduce
1) CIS deployment args:
args: [
              "--bigip-username=$(BIGIP_USERNAME)",
              "--bigip-password=$(BIGIP_PASSWORD)",
              "--bigip-url=10.x.y.223",
              "--bigip-partition=ocp01",
              "--namespace=ns05",
              "--namespace=ns06",
              "--pool-member-type=cluster",
              "--filter-tenants=true",
              "--insecure=true",
              "--extended-spec-configmap=kube-system/f5-apps-cm",
              "--controller-mode=openshift",
              "--static-routing-mode=true",
              "--orchestration-cni=ovn-k8s",
              "--as3-validation=true",
              "--override-as3-declaration=kube-system/snat-apps-override",
              "--log-as3-response=true",
              "--log-level=DEBUG",
          ]

2) extended ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: f5-apps-cm
    namespace: kube-system
    labels:
        f5nr: "true"
data:
    extendedSpec: |
        extendedRouteSpec:
        - namespace: ns05
          vserverAddr: 10.x.z.204
          vserverName: APP03-NGINX_V
          allowOverride: true
        - namespace: ns06
          vserverAddr: 10.x.z.205
          vserverName: APP06-APACHE_V
          allowOverride: true
```
3) [admin@lb01:Active:Standalone] config # tmsh show running-config ltm snatpool
```
ltm snatpool APP03_NGINX_SPL {
    members {
        10.158.149.214
    }
}
ltm snatpool APP06_APACHE_SPL {
    members {
        10.158.149.215
    }
}
```
4) override ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5type: virtual-server
    overrideAS3: "true"
  name: snat-apps-override-cm
  namespace: kube-system
data:
  template: |
    {
        "declaration": {
            "ocp01": {
                "AA": {
                    "APP03_NGINX_V_80": {
                        "snat": {
                            "bigip": "/Common/APP03_NGINX_SPL"
                        }
                    },
                    "APP06_APACHE_V_80": {
                        "snat": {
                            "bigip": "/Common/APP06_APACHE_SPL"
                        }
                    }
                }
            }
        }
    }
```

Expected Result
For each created Virtual Server, SNAT Pool should be applied. If possible, at the level extended ConfigMap or using override AS3 ConfigMap.

Actual Result
Override AS3 ConfigMap does not modify Source Address Translation for SNAT with SNAT Pool APP03_NGINX_SPL and APP06_APACHE_SPL respectively. Manually modified Virtual Servers configuration on big-ip, applies SNAT Pools.

**Comment by vklohiya** [comment]
@aswoad-tech , Override configmap is not supported with NextGen Routes. To configure the SNAT to a route group you can use the policy CR. Here are the examples for your reference:

https://github.com/F5Networks/k8s-bigip-ctlr/blob/2.x-master/docs/config_examples/customResource/Policy/sample-policy.yaml

https://github.com/F5Networks/k8s-bigip-ctlr/blob/2.x-master/docs/config_examples/customResource/Policy/extended-configmap-routes-with-policy.yaml

**Comment by aswoad-tech** [comment]
I removed the override-as3 from CIS deployment args and modified the extended ConfigMap to:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-apps-cm
  namespace: kube-system
data:
  extendedSpec: |
    extendedRouteSpec:
    - namespace: ns05
      vserverAddr: 10.158.149.204
      vserverName: APP03-NGINX_V
      allowOverride: true
      policyCR: kube-system/app03-nginx-policy
    - namespace: ns06
      vserverAddr: 10.158.149.205
      vserverName: APP06-APACHE_V
      allowOverride: true
```

with following policy:

```
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: app03-nginx-policy
  namespace: kube-system
spec:
  snat: /Common/APP03_NGINX_SPL
```

CIS pod logs errors as in cis-logs.txt attachment and vserverName: APP03-NGINX_V is not creating on big-ip (while serverName: APP 06-APACHE _V without policy is created).

[cis-logs.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/14345631/cis-logs.txt)


My routes yaml is:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: ns05
  labels:
    f5nr: "true"
  name: app03-nginx
spec:
  host: app03-nginx.lab.org
  path: "/"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: app03-nginx
```
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: ns06
  labels:
    f5nr: "true"
  name: app06-apache
spec:
  host: app06-apache.lab.org
  path: "/"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: app06-apache
```
