### ISSUE TITLE
EDNS doesnt work after 2.14.0

### ISSUE THREAD

**Issue by skenderidis** [F5Networks/k8s-bigip-ctlr#3299]
#### Setup Details
 CIS Version : 2.14.0 , 2.15.0, 2.15.1     
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.49      
 Agent Mode: CCCL       
 Orchestration: K8S     
 Orchestration Version:       
 Pool Mode: Cluster      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Steps To Reproduce
1) Create the VS manifest
```
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: sample-virtual
  namespace: default
spec:
  host: example.com
  pools:
  - monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: http
    path: /
    service: svc-1
    servicePort: 80
  virtualServerAddress: 172.16.3.4
```

2) Create the EDNS manifest
```
apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  labels:
    f5cr: "true"
spec:
  domainName: example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/GSLBServer
    monitor:
      type: https
      send: "GET /"
      recv: ""
      interval: 10
      timeout: 10
```
3) Check that the EDNS has been deployed.
