### ISSUE TITLE
Consistent specification of pre-release images in the Operator

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#3601]
#### Title
Consistent specification of pre-release images in the Operator

#### Description
At present, in order to be able to use a pre-release/bugfix image, the customer have to specify the following:

```
  image:
    repo: k8s-bigip-ctlr-devel
    user: quay.io/f5networks
  version: 747c54aea334532b39bb611bd04d16036d8f6b05
```
where user doesn´t make sense. 

#### Actual Problem
The syntax is confusing when using these images and can lead to errors in production.
