### ISSUE TITLE
CIS Integration ClusterIP mode

### ISSUE THREAD

**Issue by Chup4Chups** [F5Networks/k8s-bigip-ctlr#3807]
I am doing a PoC to integrate CIS (2.19.1) with OpenShift (4.16, using default ovn-kubernetes)
I have deployed an OpenShift Cluster and BIG-IP VE in different subnet.

```
args: [
  # See the k8s-bigip-ctlr documentation for information about
  # all config options
  # https://clouddocs.f5.com/containers/latest/
  "--bigip-username=$(BIGIP_USERNAME)",
  "--bigip-password=$(BIGIP_PASSWORD)",
  "--bigip-url=10.192.125.60",
  "--bigip-partition=OpenShift",
  "--namespace=cafe",
  "--orchestration-cni=ovn-k8s",
  "--static-routing-mode=true",
  "--pool-member-type=cluster",
  "--insecure=true",
  "--manage-routes=true",
  "--extended-spec-configmap="kube-system/extended-cm"
  "--controller-mode="openshift"
  "--as3-validation=true",
  "--log-as3-response=true",
```
When deploying CIS with ClusterIP mode, The BIG-IP directly communicate with the pod network. 
I have observed that CIS attempt to configure static routes on the BIG-IP but this step fails because the BIG-IP doesn't have a network interface in openshift network.
When trying to configure the same static route manually, I have the same error as in the CIS pod log.
![Image](https://github.com/user-attachments/assets/db8fa9cd-eb57-4e05-9730-b4cdcd97f00d)
10.1.0.132 ->worker node IP
10.129.2.0/23 -> pod network on worker 132
 
Does the ClusterIP mode requires the BIG-IP to be in the same network as openshift cluster ? (which would be surprising in term of architecture), or did I miss something about the way to use ClusterIP mode ?

Thanks in advance for your help.

**Comment by trinaths** [comment]
@Chup4Chups 

- Use pool-member-type=nodeport instead of cluster. This will make BIG-IP reach pods via OpenShift Node IPs and NodePorts → No static routes needed.

- If you must use ClusterIP mode

You need BIG-IP to reach Pod network directly.

Options:
	1.	Extend BIG-IP network to OVN pod network (not ideal in production).
	2.	Create a VXLAN tunnel between BIG-IP and OpenShift OVN Overlay.
	3.	Use BIG-IP as External Router with OVN Route Distribution → Complex setup.
	4.	Use F5 Container-Networking solution or BIG-IP CNI integration → Adds networking between BIG-IP and pod networks.

- If CIS is managing static routes but fails:
   Pre-create static routes manually on BIG-IP to all pod CIDRs via OpenShift Node IPs and retry.

Share your findings to automation_toolchain_pm [automation_toolchain_pm@f5.com].

**Comment by Chup4Chups** [comment]
Hi @trinaths 
Thanks for your answer and sharing these information.
I have redeployed CIS with pool-member-type=nodeport and observed the following:
- Services of type "clusterIP" are ignored and I needed to switch the service to "nodeport"
- CIS create a pool with members corresponding to my nodes using the ephemeral port given by the nodeport service.

This is my CIS config (using operator)
```yaml
apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  name: f5bigipctlr
  namespace: openshift-operators
spec:
  ingressClass:
    create: false
    defaultController: false
    ingressClassName: f5
  resources: {}
  rbac:
    create: true
  version: latest
  serviceAccount:
    create: true
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    user: f5networks
  namespace: kube-system
  args:
    orchestration_cni: ovn-k8s
    manage_routes: true
    agent: as3
    log_level: DEBUG
    route_vserver_addr: 10.0.1.101
    bigip_partition: cis_managed_partition
    bigip_url: 10.0.0.11
    log_as3_response: true
    insecure: true
    pool_member_type: nodeport
    route_label: test
  bigip_login_secret: f5-login
```

I have created the following deployment to test the integration and so far it "works".
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-blue
  template:
    metadata:
      labels:
        app: app-blue
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        env:
        - name: RESPONSE
          value: "cluster OCP1 / L7 route BLUE: shop.multicluster.com/"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumemounts:
        - name: tmp
          mountpath: "/tmp"
      volumes:
      - name: tmp
        emptydir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: service-blue
  namespace: applications
  labels:
    app: app-blue
spec:
  ports: 8080
  - name: app-blue-svc
    port: 
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: app-blue
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-blue
  namespace: applications
  labels:
    f5nr: 'true'
    f5type: test
spec:
  host: shop.multicluster.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: service-blue
    weight: 100
  wildcardPolicy: None
```

But from what I understood, the route I deployed is only used by CIS to configured the BIG-IP resources (Virtual Server, LTM policy and Pool members), however, the traffic goes directly to kube-proxy -> nodeport service, and therefore bypass the "default router" (haproxy / ingress controller).
Is this correct ? Are you aware of any example / documentation showing a CIS integration for 2-tier deployments with pool-member-type: nodeport ?

https://community.f5.com/kb/technicalarticles/f5-big-ip-deployment-with-openshift---per-application-2-tier-deployments/327094
