### ISSUE TITLE
Bug: pools component not required when using defaultPool

### ISSUE THREAD

**Issue by artgmolina** [F5Networks/k8s-bigip-ctlr#3848]
Setup Details
	•	CIS Version: 2.18.1
	•	Image: f5networks/k8s-bigip-ctlr:2.18.1
	•	BIG-IP Version: v17
	•	AS3 Version: 3.54
	•	Agent Mode: AS3
	•	Orchestration Platform: OpenShift with OVN

Description

According to the documentation, the pools component is required in the VirtualServer specification. However, in a two-tier architecture, when using a defaultPool with a reference: bigip, the pools block is not necessary and the configuration still works correctly.

This suggests a mismatch between the documented requirement and the actual controller behavior. In this case, the backend service (HAProxy) is capable of handling host/path routing internally, and the BIG-IP simply forwards traffic using the configured default pool.

Example Manifest

```yaml
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: route-a
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  bigipRouteDomain: 0
  defaultPool:
    name: /Common/haproxy_pool
    reference: bigip
  host: www.sc-twotier.com
  hostAliases:
    - www.testing.com
    - www2.sc-twotier.com
  hostGroup: sc-twotier.com
  tlsProfileName: reencrypt-tls
  virtualServerAddress: 10.1.10.104
```

![Screenshot of the behavior](https://github.com/user-attachments/assets/c00a1cb5-a1b2-4e42-a823-da2cff3c3777)

Steps to Reproduce
	1.	Create a VirtualServer CRD as shown above, with only defaultPool defined (no pools block).
	2.	Apply the manifest in an OpenShift cluster with CIS configured.

Expected Result

The controller should either:
	•	Accept and apply the VirtualServer correctly with only defaultPool, or
	•	Reject the configuration if pools are truly required, providing a clear error.

Actual Result

The configuration is accepted, deployed correctly, and the BIG-IP only contains a reference to the single pool (/Common/haproxy_pool), keeping the configuration minimal and clean.

Additional Notes

This behavior is useful in the following scenarios:
	•	All traffic can go to a single backend.
	•	The backend (e.g., HAProxy) handles routing logic internally.
	•	You want to reduce object creation and keep BIG-IP configuration streamlined.

Suggestion

Please clarify in the documentation whether the pools component is truly required when defaultPool is used with reference: bigip.
