### ISSUE TITLE
Ability to Add Arbitrary Additional Pool Members For Mixed Environments

### ISSUE THREAD

**Issue by Vacant0mens** [F5Networks/k8s-bigip-ctlr#3852]
## Title
Arbitrary Additional Pool Members For Mixed Environments

## Description
For environments where some applications are hosted in VM's, on hardware, or another part of a given infrastructure (outside of Kubernetes, but still accessible to BigIP), it would be incredibly helpful to have the ability to specify an IP or Node (or multiple) to be included in the Pool configuration that CIS sends to AS3. 

## Actual Problem
In mixed environments, especially when transitioning/migrating to a Kubernetes infrastructure, the only way to load balance across the current/legacy environment and the Kubernetes+CIS environment is to use a custom ConfigMap object with an AS3 declaration template that gets updated by labeling the Service objects in Kubernetes, and to use a secondary pool with an iRule to "load balance" across the two pools.

Example with NGINX Ingress Controller in front of pods:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: bigip-vs-loadbalance
  namespace: f5-ingress
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/main/schema/latest/as3-schema.json",
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.21.0",
        "label": "Test Label",
        "remark": "Test Remark",
        "k8s": {
          "class": "Tenant",
          "example": {
            "class": "Application",
            "template": "generic",
            "vs_test": {
              "class": "Service_HTTPS",
              "virtualPort": 443,
              "redirect80": true,
              "virtualAddresses": [
                "172.16.0.23"
              ],
              "iRules": [
                "rule_LoadBalance"
              ],
              "pool": "nginx_pool",
              "serverTLS": "test_TLS",
              "clientTLS": {
                "bigip": "/Common/serverssl-insecure-compatible"
              }
            },
            "test_TLS": {
              "class": "TLS_Server",
              "label": "tls_example label",
              "remark": "tls_example remark",
              "requireSNI": true,
              "ciphers": "DEFAULT",
              "tls1_0Enabled": false,
              "tls1_1Enabled": false,
              "ssl3Enabled": false,
              "sslEnabled": false,
              "certificates": [
                {
                  "sniDefault": true,
                  "certificate": "test_certificate"
                }
              ]
            },
            "test_certificate": {
              "label": "cert_example label",
              "remark": "cert_example remark",
              "class": "Certificate",
              "certificate": "-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----",
              "privateKey":  "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----",
              "chainCA":     "-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----"
            },
            "rule_LoadBalanceBeta": {
              "class": "iRule",
              "iRule": "when HTTP_REQUEST {\n    set default_pool [LB::server pool] \n    if { [expr { rand() < 0.5 }] } {\n        pool /k8s/example/pool_testVMs\n    } else {\n        pool $default_pool\n    }\n}"
            },
            "nginx_pool": {
              "class": "Pool",
              "monitors": [
                "https"
              ],
              "members": [
                {
                  "servicePort": 443,
                  "serverAddresses": [],
                  "shareNodes": false
                }
              ]
            },
            "pool_testVMs": {
              "class": "Pool",
              "monitors": [
                "https"
              ],
              "members": [
                {
                  "servicePort": 443,
                  "serverAddresses": [
                    "10.0.0.25"
                  ],
                  "shareNodes": true
                },
                {
                  "servicePort": 443,
                  "serverAddresses": [
                    "10.0.0.24"
                  ],
                  "shareNodes": true
                }
              ]
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-controller
  namespace: f5-ingress
  labels:
    cis.f5.com/as3-tenant: k8s
    cis.f5.com/as3-app: example
    cis.f5.com/as3-pool: nginx_pool
  annotations:
    nodeportlocal.antrea.io/enabled: "true"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx
    # app: nginx-ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test-namespace
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - app1.example.com
      secretName: test_cert
  rules:
  - host: app1.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app1
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2-ingress
  namespace: test-namespace
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - app2.example.com
      secretName: test_cert
  rules:
  - host: app2.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app2
              port:
                number: 80
---
```

## Solution Proposed
Proposals:
1. Annotations on the Ingress object to indicate "additional pool members" as an AS3-compatible snippet (i.e. JSON, or list of IP addresses, etc.) that can be injected into the AS3 declaration before CIS sends the request.
2. Property/ies in the Virtual Server CRD spec for "additional/non-K8s pool members" that CIS can then translate into items that can be appended to the "members" list in the Pool class object in the AS3 declaration.

## Alternatives
As shown in `Actual Problem` above, the only real solution is complex and requires knowledge of the AS3 Declaration schema.

## Additional context
I realize this use case isn't exactly the most popular, but it would aid some teams in migrating from current infrastructure into a Kubernetes-based environment more smoothly and with minimal interruptions to provided services.
