### ISSUE TITLE
ltmPolicies Component in POLICY CR does not work

### ISSUE THREAD

**Issue by artgmolina** [F5Networks/k8s-bigip-ctlr#3889]
#### Setup Details
 CIS Version : 2.X      
 Build: f5networks/k8s-bigip-ctlr:2.18.1   
 BIGIP Version: Big IP 17.x

#### Description  
ltmpolicies component does not work. There is not any example but I tried all combinations and they don't work. I also copied an example from an iRule component where secure, insecure and priority are present... and still does not work.

Policy Components
---
**LTM Policy Components**

Parameter | Type | Required | Default | Description
-- | -- | -- | -- | --
insecure | String | Optional | N/A |  
secure | String | Optional | N/A |  
priority | String | Optional | N/A | Defines the level of priority. Allowed values are low and high.

Example:

```yaml
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: sample-policy
  namespace: default
spec:
  snat: auto
  l7Policies:
    waf: /Common/WAF_Policy
  ltmPolicies:
    insecure: /Common/ltm_policy
    secure: /Common/ltm_policy
...
```

#### Expected Result 
An existing LTM policy is associated with such virtual server.

#### Actual Result  
Such parameters are ignored

**Comment by trinaths** [comment]
@artgmolina 
Please update CIS to 2.20 and CRD schema and share your findings.

**Comment by artgmolina** [comment]
I have updated CIS to 2.20.1 and It is still not working. I have included in the Policy CR an iRule which has the same structure and it is working. The iRule is corrected attached but not the existing LTM policy created in Common.

```
apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: l7-policy-www
  namespace: nginx-ingress
spec:
  snat: auto
  ltmPolicies:
    secure: /Common/ltmpolicysample
    insecure: /Common/ltmpolicysample
    priority: high
  iRules:
    secure: /Common/irule1
    insecure: /Common/irule1
    priority: high
```

<img width="894" height="888" alt="Image" src="https://github.com/user-attachments/assets/b9d7eb32-7bc3-4d45-8f74-a72e5dd2c553" />

Below you can check that the policy is already created in /Common but not assigned.

<img width="1330" height="516" alt="Image" src="https://github.com/user-attachments/assets/f2d9f9be-7e72-4bdf-a8ca-a6f6941b6314" />
