### ISSUE TITLE
Documentation: Clarify deploying for HA pair of F5 BIG-IP LBs

### ISSUE THREAD

**Issue by djtaylor** [F5Networks/k8s-bigip-ctlr#450]
#### Description
Unless I have missed some piece of documentation (would be happy to get a link as a comment and close this out), its is unclear how to manage configuration synchronization between an active/standby pair of F5 load balancers. An extra readme, example deployment file, or updates would be nice to clarify this.

#### Kubernetes Version
1.7.5+coreos.1

#### Controller Version
1.3.0

#### BIG-IP Version
11.6.0

#### Unresolved Questions
If we have automatic sync disabled, what is the best way to construct a deployment to make sure the configuration stays in sync between load balancers?

Should we have automatic sync enabled in this instance?

Would something this suffice to keep the configuration in sync?

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-bigip-ha-lb-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr-ha
      labels:
        app: k8s-bigip-ctlr-ha
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr-ha1
          image: "f5networks/k8s-bigip-ctlr:1.3.0"
          command:
            - /app/bin/k8s-bigip-ctlr
          args:
            - --bigip-username=$(BIGIP_USERNAME)
            - --bigip-password=$(BIGIP_PASSWORD)
            - --bigip-url=$(BIGIP_URL)
            - --bigip-partition=$(BIGIP_PARTITION)
            - --namespace-label=f5-ha
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: password
            - name: BIGIP_URL
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: url1
            - name: BIGIP_PARTITION
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: partition

        - name: k8s-bigip-ctlr-ha2
          image: "f5networks/k8s-bigip-ctlr:1.3.0"
          command:
            - /app/bin/k8s-bigip-ctlr
          args:
            - --bigip-username=$(BIGIP_USERNAME)
            - --bigip-password=$(BIGIP_PASSWORD)
            - --bigip-url=$(BIGIP_URL)
            - --bigip-partition=$(BIGIP_PARTITION)
            - --namespace-label=f5-ha
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: password
            - name: BIGIP_URL
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: url2
            - name: BIGIP_PARTITION
              valueFrom:
                secretKeyRef:
                  name: bigip-params-ha
                  key: partition
```
