### ISSUE TITLE
When updating routes, old service pools are not removed until after a refresh cycle

### ISSUE THREAD

**Issue by russokj** [F5Networks/k8s-bigip-ctlr#471]
#### Description
In Openshift, if a route changes which service it is using (for instance, upgrading to a new version), the pool for the old service it left configured on the BIG-IP until the next refresh cycle.  To test, configure two services in openshift: svc-v1 & svc-v2. Then configure a route to use svc-v1. When the route is changed to use svc-v2, the BIG-IP will show the pools for both svc-v1 and svc-v2 until either the next refresh cycle of the controller, or the user deletes the service svc-v1.

#### Kubernetes Version
Openshift v1.4.1

#### Controller Version
master as of 1/3/18

#### BIG-IP Version
BIG-IP 12.1.0 Build 1.0.1447 Hotfix HF1

#### Diagnostic Information
The following was the initial route definition before switch the service to svc-v2:
```
apiVersion: v1
kind: Route
metadata:
  name: foo-com
  namespace: default
spec:
  host: foo.com
  path: /foo
  to:
    kind: Service
    name: svc-v1
```
