### ISSUE TITLE
Policy rules for routes are not removed when no longer needed

### ISSUE THREAD

**Issue by russokj** [F5Networks/k8s-bigip-ctlr#484]
#### Description
Policy rules are left configured when no longer needed.  For instance, if a route is configured with TLS, a policy(openshift_secure_routes) rule is created for  the virtual server https-ose-vserver.  If no other resources are configured, there will not be a rule for the policy openshift_unsecure_routes attached to the virtual server named ose-vserver. 

If the route is then updated to run unsecure traffic, then a rule will be attached to the virtual server ose-vserver policy (openshift_unsecure_routes) as expected.  However, the https-ose-vserver policy (openshift_secure_routes) will still show a rule.  This rule will not be removed until the controller is restarted or the route itself is completely removed.

#### Kubernetes Version
Openshift v1.4.1

#### Controller Version
master as of 1/15/2018

#### BIG-IP Version
BIG-IP 12.1.0 Build 1.0.1447 Hotfix HF1

#### Diagnostic Information
Initial Configuration for Route:
```
apiVersion: v1
kind: Route
metadata:
  name: foo-com
  namespace: default
spec:
  host: foo.com
  tls:
    certificate: ...
    destinationCACertificate: ...
    key: ...
    termination: reencrypt
  to:
    kind: Service
    name: svc-a
    weight: 100
```
Big-IP initial policies:
```
root@(host-)(cfg-sync Standalone)(Active)(/test)(tmos)# list ltm policy
ltm policy openshift_secure_routes {
    partition test
    rules {
        openshift_route_default_foo-com {
           ...
        }
    }
    ...
}
```
Updated Configuration for Route (changed from secure to insecure): 
```
apiVersion: v1
kind: Route
metadata:
  name: foo-com
  namespace: default
spec:
  host: foo.com
  to:
    kind: Service
    name: svc-a
    weight: 100
```
Big-IP Updated policies
```
ltm policy openshift_insecure_routes {
    partition test
    requires { http }
    rules {
        openshift_route_default_foo-com {
           ...
        }
    }
    ...
}
ltm policy openshift_secure_routes {
    partition test
    rules {
        openshift_route_default_foo-com {
           ...
        }
    }
    ...
}
```
