### ISSUE TITLE
SSL profile secret for ConfigMaps tries to use an illegal name

### ISSUE THREAD

**Issue by iljaweis** [F5Networks/k8s-bigip-ctlr#552]
#### Description
Tried to store SSL key/cert for a ConfigMap in a secret (as described in http://clouddocs.f5.com/containers/v2/kubernetes/kctlr-secrets.html). The controller expects the name of the secret to follow the same naming scheme as the BigIP ssl profile ("Partition/profile") or ("/profile"), but it seems like this would be an illegal object name in Kubernetes (a slash is not allowed).

see https://github.com/F5Networks/k8s-bigip-ctlr/blob/dffd1daa5b02a9670cc43f3712b4892532805f85/pkg/appmanager/appManager.go#L932

#### Kubernetes Version
1.9.2

#### Controller Version
1.4.1

#### BIG-IP Version
BIG-IP 13.0.0 Build 0.0.1645 Final

#### Diagnostic Information
This is my configmap:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: myweb
  namespace: bigip
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "myweb"
        },
        "frontend": {
          "virtualAddress": {
            "bindAddr": "10.160.10.169",
            "port": 443
          },
          "partition": "kubernetes",
          "mode": "http",
          "sslProfile": {
            "f5ProfileName": "myweb"
          }
        }
      }
    }
```

Debug output from k8s-bigip-ctlr:

```
2018/02/08 09:30:21 [WARNING] Profile name 'myweb' does not contain a full path.
2018/02/08 09:30:21 [DEBUG] No Secret with name '/myweb', parsing secretName as path instead.
```

So it tries to look for a secret '/myweb', but if I try to create such a secret, Kubernetes rejects it:

```
$ kubectl create secret generic /myweb --from-file=tls.crt=server.crt  --from-file=tls.key=server.key  -n bigip
The Secret "/myweb" is invalid: metadata.name: Invalid value: "/myweb": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

or:

```
$ kubectl create secret generic /myweb --from-file=tls.crt=server.crt  --from-file=tls.key=server.key  -n bigip --dry-run -o yaml > ssl-secret.yaml && kubectl apply -f ssl-secret.yaml
error: error when retrieving current configuration of:
&{0xc4200f4b40 0xc42021a230 bigip /myweb ssl-secret.yaml 0xc420fb42a0  false}
from server for: "ssl-secret.yaml": invalid resource name "/myweb": [may not contain '/']
```
