### ISSUE TITLE
when specifying healthMonitors cannot use YAML 

### ISSUE THREAD

**Issue by recursivelycurious** [F5Networks/k8s-bigip-ctlr#594]
#### Description

In kubernetes resources are commonly pure YAML. Thus I would expect to be able to specify a healthMonitor (in this case on an ingress) using

```
virtual-server.f5.com/health:
      - path: "/"
        send: "HTTP GET /"
        interval: 5
        timeout: 10
```

when the controller requires JSON

```
virtual-server.f5.com/health: |
      [
        {
          "path":     "/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        }
      ]
```
#### Kubernetes Version
1.8

#### Controller Version
1.4.2

#### BIG-IP Version
12.1

In conversation with @sjberman we were looking at:
https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/appmanager/appManager.go#L1011
