### ISSUE TITLE
[DOC] Improve f5-k8s-sample-rbac.yaml by restricting secret's access

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#612]
#### Description

The current f5-k8s-sample-rbac.yaml currently allows the f5-k8s-ctrl container to access all secrets in the system. This might be overlooked by customers when deploying the controller and increases the chance of breaching cluster security.

This can be enhanced easily with something like:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bigip-credentials-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["bigip-credentials"]
  verbs: ["get"]
- apiGroups:
[...]
```

#### Kubernetes Version

apiVersion: rbac.authorization.k8s.io/v1beta1

#### BIG-IP Version

NA
