### ISSUE TITLE
[DOC] Improve HA configuration by using failure domain labels

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/k8s-bigip-ctlr#627]
#### Description

In high available k8s deployments the label failure-domain.beta.kubernetes.io/zone is used to spread pods across nodes in independent failure domains. BIG-IPs and their controllers should be in the same failure domain. 

This is documented in https://kubernetes.io/docs/admin/multiple-zones/

How to place the BIG-IP in the same failure domain as a given set of k8s nodes is out of scope because it depends in the underlying infrastructure but we should indicate that ideally:

1. the BIG-IP units of a HA/Scale-N cluster should be placed in different failure domains,

2. the BIG-IP controllers should be in the same failure domain of their respective BIG-IP units

To achieve (2) we need to 

a) Assign a failure-domain.beta.kubernetes.io/zone label to the corresponding nodes, ie:

```
[root@ibmcloud1 k8s-bigip-ctrl.kube-system]# kubectl label nodes 10.105.212.201 failure-domain.beta.kubernetes.io/zone=east
node "10.105.212.201" labeled
[root@ibmcloud1 k8s-bigip-ctrl.kube-system]# kubectl label nodes 10.105.212.202 failure-domain.beta.kubernetes.io/zone=west
node "10.105.212.202" labeled
```

b) Indicate to the BIG-IP controller Deployment file the corresponding zone, ie:

```
[root@ibmcloud1 k8s-bigip-ctrl.kube-system]# cat k8s-bigip1-ctrl.zone-east.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-k8s-controller1
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: f5-k8s-controller1
      labels:
        app: f5-k8s-controller1
    spec:
      serviceAccountName: bigip-ctlr
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: east
      containers:
```

And then create the BIG-IP controller instances normally:

```
[root@ibmcloud1 k8s-bigip-ctrl.kube-system]# kubectl create -f k8s-bigip1-ctrl.zone-east.yaml
deployment "f5-k8s-controller1" created
[root@ibmcloud1 k8s-bigip-ctrl.kube-system]# kubectl create -f k8s-bigip2-ctrl.zone-west.yaml
deployment "f5-k8s-controller2" created
```

c) Verification is as follows:

```
[root@ibmcloud1 k8s-bigip-ctrl.kube-system]# kubectl get pods -o wide -n kube-system | grep f5
f5-k8s-controller1-3603337196-9bf74                       1/1       Running   0          7m        10.106.80.53     10.105.212.201
f5-k8s-controller2-2459851204-rp2zm                       1/1       Running   0          24s       10.106.80.75     10.105.212.202
```
