### ISSUE TITLE
policies remain when reconfiguring from more complex to simpler ingress 

### ISSUE THREAD

**Issue by recursivelycurious** [F5Networks/k8s-bigip-ctlr#635]
#### Description
When using `kubectl apply` to configure an ingress from multiple paths without specific hosts

```
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: svc-1-demo-web-app
          servicePort: 80
        path: /foo
      - backend:
          serviceName: svc-2-demo-web-app
          servicePort: 80
        path: /bar
      - backend:
          serviceName: svc-3-demo-web-app
          servicePort: 80
        path: /baz/qux
```
to a simpler spec:

```
spec:
  backend:
    serviceName: svc-1-demo-web-app
    servicePort: 80
```
An unexpected policy remains:

```
{
    "kind": "tm:ltm:policy:rules:conditions:conditionscollectionstate",
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~test~ingress_172-16-3-59_80/rules/ingress__foo_ingress_default_svc-1-demo-web-app/conditions?ver=12.1.2",
    "items": [
        {
            "kind": "tm:ltm:policy:rules:conditions:conditionsstate",
            "name": "0",
            "fullPath": "0",
            "generation": 3480,
            "selfLink": "https://localhost/mgmt/tm/ltm/policy/~test~ingress_172-16-3-59_80/rules/ingress__foo_ingress_default_svc-1-demo-web-app/conditions/0?ver=12.1.2",
            "caseInsensitive": true,
            "equals": true,
            "external": true,
            "httpUri": true,
            "index": 1,
            "pathSegment": true,
            "present": true,
            "remote": true,
            "request": true,
            "values": [
                "foo"
            ]
        }
    ]
}
```

This type of simplification of configuration may occur during a rollback, using either `kubectl apply` or using `helm rollback`. Note that nodes appear healthy to the monitors, and the pools are available, but traffic is dropped due to the policy.

```
curl 1.2.3.4:80 
# curl: (56) Recv failure: Connection reset by peer
curl 1.2.3.4:80/foo
# Hello from ... (success)
```

#### Kubernetes Version
1.8

#### Controller Version
From controller log:
`Starting: Version: 1.5.0-WIP, BuildInfo: n914-358525313`

#### BIG-IP Version
12.1.2

#### Diagnostic Information

Initial ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/health: |
      [
        {
          "path":     "/foo",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        },
        {
          "path":     "/bar",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        },
        {
          "path":     "/baz/qux",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        }
      ]
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/ip: 1.2.3.4
    virtual-server.f5.com/partition: test
  name: manual-ingress-test
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: svc-1-demo-web-app
          servicePort: 80
        path: /foo
      - backend:
          serviceName: svc-2-demo-web-app
          servicePort: 80
        path: /bar
      - backend:
          serviceName: svc-3-demo-web-app
          servicePort: 80
        path: /baz/qux
```

updated configuration
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    virtual-server.f5.com/health: |
      [
        {
          "path":     "/",
          "send":     "HTTP GET /",
          "interval": 5,
          "timeout":  10
        }
      ]
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/ip: 1.2.3.4
    virtual-server.f5.com/partition: test
  name: manual-ingress-test
  namespace: default
spec:
  backend:
    serviceName: svc-1-demo-web-app
    servicePort: 80
```
