### ISSUE TITLE
Kubernetes Liveness and Readiness Probes

### ISSUE THREAD

**Issue by coulsonr** [F5Networks/k8s-bigip-ctlr#815]
#### Description
Does the Big IP Controller have any commands internal to the container that can be used to wire up Kubernetes Liveness and Readiness Probes? I've read the basic deployment information here: 

https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html#kctlr-basic-deploy

but I don't see any mention specific to liveness and readiness probes. Here's the link to K8's liveness and readiness probes: 

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes

Specific excerpts from that link: 
```
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
```
```
readinessProbe:
  exec:
    command:
    - cat
    - /tmp/healthy
  initialDelaySeconds: 5
  periodSeconds: 5
```

#### Kubernetes Version
1.12

#### Controller Version
1.7.1

#### BIG-IP Version
13

#### Diagnostic Information
The reason this question is being asked is because we have seen issues where a big ip controller will simply stop doing it's work, and we've had to manually restart the pod in Kubernetes in order for the controller to start working again. If we could feed Kubernetes a liveness and readiness probe, Kubernetes could manage this restart for us.

**Comment by vincentmli** [comment]
this sounds a good idea, livenessProbe seems make more sense here to the bigip controller pod

**Comment by vincentmli** [comment]
the controller already have a built in http listener serving on path /health to monitor if the python writer process running in the controller container, maybe this could serve as a starter, I am not sure though if simply checking a running process exist in the controller pod is enough health sign under various unknown "freezing" conditions, here is my quick test example( removed the irrelevant part from the deployment):

<pre>

        command:
        - /app/bin/k8s-bigip-ctlr
        image: f5networks/k8s-bigip-ctlr:1.7.1
        imagePullPolicy: Always
        livenessProbe:
            httpGet:
        # when "host" is not defined, "PodIP" will be used
        # host: my-host
        # when "scheme" is not defined, "HTTP" scheme will be used. Only "HTTP" and "HTTPS" are allowed
        # scheme: HTTPS
                path: /health
                port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
        name: cc-liveprobe
</pre>

here is the code to handle the /health 
https://github.com/vincentmli/k8s-bigip-ctlr/blob/master/cmd/k8s-bigip-ctlr/main.go#L706
<pre>
	http.Handle("/health", hc.HealthCheckHandler())
	bigIPPrometheus.RegisterMetrics()
	go func() {
		log.Fatal(http.ListenAndServe(*httpAddress, nil).Error())
	}()
</pre>

https://github.com/vincentmli/k8s-bigip-ctlr/blob/master/pkg/health/health.go

**Comment by mdditt2000** [comment]
CONTCNTR-178

**Comment by coulsonr** [comment]
Mark, what is CONTCNTR-178?

**Comment by mdditt2000** [comment]
@coulsonr internal Jira tracking. I am request dev to scope this enhancement. Will provide release and timeline soon.

**Comment by mitchellmaler** [comment]
Is there any status on this enhancement request? We are looking to use the controller for ingress but are worried we won't know if is is not healthy using OOTB probes. We are investigating using the metrics but it doesn't give enough to know if it is healthy #930

**Comment by mdditt2000** [comment]
Added to CIS 

https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-app-install.html#run-health-checks

```
#Liveness Probe Configuration to be added under command
        livenessProbe:
           failureThreshold: 3
           httpGet:
              path: /health
              port: 8080
              scheme: HTTP
           initialDelaySeconds: 15
           periodSeconds: 15
           successThreshold: 1
           timeoutSeconds: 15
        #Readiness Probe Configuration to be added under command  
        readinessProbe:
           failureThreshold: 3
           httpGet:
              path: /health
              port: 8080
              scheme: HTTP
           initialDelaySeconds: 30
           periodSeconds: 30
           successThreshold: 1
           timeoutSeconds: 15
```
