### ISSUE TITLE
Ingress Resource - Strip Prefix from URL for path based routing

### ISSUE THREAD

**Issue by neeseius** [F5Networks/k8s-bigip-ctlr#835]
#### Description
It would be very useful if there were an annotation for, by default, stripping the path-prefix from paths.
example:
```
  - host: apitesting.example.com
    http:
      - path: /testenv3/api1
        backend:
          serviceName: testenv3-api1
          servicePort: 443
      - path: /testenv1/api1
        backend:
          serviceName: testenv1-api1
          servicePort: 443
```
So paths would be modified like below when they hit the backend service:
https://apitesting.example.com/testenv3/api1/check/token
becomes:
/check/token
instead of:
/testenv3/api1/check/token

This is useful because the backend service may not understand the paths being defined in the Ingress. We can then utilize paths defined in the Ingress to do a lot more and act as an api-gateway for example.
