### ISSUE TITLE
Missing Prometheus metrics for bigip-ctlr health

### ISSUE THREAD

**Issue by liorfranko** [F5Networks/k8s-bigip-ctlr#930]
#### Description
Missing Prometheus metrics that shows when the bigip-ctlr health.
For example, when it can't reaching the F5's API, we tested connectivity issues between the pod and the external BIGIP but we don't a way to raise alerts from the current Prometheus metrics.
There should be many metrics shows the health of the bigip-ctlr.

#### Kubernetes Version
1.11.6

#### Controller Version
1.8.1

#### BIG-IP Version
12.1.2

**Comment by mdditt2000** [comment]
Pull request adds prometheus support for monitoring nodes, services etc but not fo the bigip-ctlr health https://github.com/F5Networks/k8s-bigip-ctlr/pull/384
Tracking CONTCNTR-855

**Comment by mdditt2000** [comment]
Post CIS 2.x initiative

**Comment by mdditt2000** [comment]
Updated prometheus document https://github.com/mdditt2000/prometheus

Please look at configmap
```
- job_name: cis
        scrape_interval: 10s
        metrics_path: '/metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: k8s_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: k8s_pod_name
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: ${1}:8080
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: f5-bigip-ctlr 
```
