### ISSUE TITLE
BIG-IP configurations created via AS3 declarations not removed after a the ConfigMap declaring them is deleted

### ISSUE THREAD

**Issue by Rodalli** [F5Networks/k8s-bigip-ctlr#946]
#### Description
After provisioning resources on the BIG-IP via an AS3 declaration, CIS doesn't delete provisioned resources on the BIG-IP device if a ConfigMap containing the AS3 declaration is deleted. This is unexpected behavior vs. how the controller reacts when using F5 Resources to manage configuration.

Say for instance you have this Service defined:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"app1"},"name":"app1-service","namespace":"app1"},"spec":{"ports":[{"name":"https","port":8443,"protocol":"TCP","targetPort":8443}],"selector":{"app":"crp"},"type":"NodePort"}}
  creationTimestamp: "2019-06-11T16:07:30Z"
  labels:
    app: crp
    cis.f5.com/as3-app: app1_web_vs
    cis.f5.com/as3-pool: app1_web_pool
    cis.f5.com/as3-tenant: app1_k8s
  name: app1-service
  namespace: app1
  resourceVersion: "6661912"
  selfLink: /api/v1/namespaces/app1/services/app1-service
  uid: 03938c71-8c63-11e9-836d-005056992993
spec:
  clusterIP: 10.32.0.62
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31340
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: app1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

...and this ConfigMap with an AS3 declaration...

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-dev.vs
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.11.0",
            "id": "app1-web-f5-declaration-01",
            "label": "App1 F5 Config",
            "updateMode": "selective",
            "app1_k8s": {
                "class": "Tenant",
                "app1_web_vs": {
                    "class": "Application",
                    "template": "tcp",
                    "serviceMain": {
                        "class": "Service_TCP",
                        "virtualAddresses": [
                            "192.168.1.1"
                        ],
                        "pool": "crp_web_pool",
                        "virtualPort": 443
                    },
                    "app1_web_pool": {
                        "class": "Pool",
                        "loadBalancingMode": "least-connections-member",
                        "members": [{
                            "servicePort": 0,
                            "serverAddresses": []
                        }],
                        "monitors": [
                            "tcp"
                        ]
                    }
                }
            }
        }
    }
```

If you deleted the ConfigMap from the cluster, you would expect the BIG-IP Controller for k8s to remove the associated resources configured on the BIG-IP, as it does if these are declared with F5 Resources instead of AS3 declarations. Instead, it does nothing and leaves the BIG-IP littered with these configuration objects.

![image](https://user-images.githubusercontent.com/25597644/59787766-6c7ecb80-9287-11e9-923d-3ba9ce26bc8d.png)

Is this expected behavior?

#### Kubernetes Version
1.12.3

#### Controller Version
1.9

#### BIG-IP Version
12.1.3

**Comment by ssurenr** [comment]
This is by design and it is expected behavior. Removing resources created by an AS3 declaration is a two-step process.
1. Update the AS3 template in the config map to an empty declaration. In your case:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-dev.vs
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.11.0",
            "id": "app1-web-f5-declaration-01",
            "label": "App1 F5 Config",
            "updateMode": "selective",
            "app1_k8s": {
                "class": "Tenant",
            }
        }
    }
```
2. Then delete the configmap.
